//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatManagement.ServicePosition {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<int> IDJourneyField;
        
        private System.Nullable<double> LongitudeField;
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<System.DateTime> TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OceansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServicePosition.Journey JourneyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IDJourney {
            get {
                return this.IDJourneyField;
            }
            set {
                if ((this.IDJourneyField.Equals(value) != true)) {
                    this.IDJourneyField = value;
                    this.RaisePropertyChanged("IDJourney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Oceans {
            get {
                return this.OceansField;
            }
            set {
                if ((object.ReferenceEquals(this.OceansField, value) != true)) {
                    this.OceansField = value;
                    this.RaisePropertyChanged("Oceans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BoatManagement.ServicePosition.Journey Journey {
            get {
                return this.JourneyField;
            }
            set {
                if ((object.ReferenceEquals(this.JourneyField, value) != true)) {
                    this.JourneyField = value;
                    this.RaisePropertyChanged("Journey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Journey", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Journey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<int> IDBoatField;
        
        private System.Nullable<int> BeginPositionField;
        
        private System.Nullable<int> EndPositionField;
        
        private System.Nullable<double> TimeProvideField;
        
        private System.Nullable<System.DateTime> TimeBeginField;
        
        private System.Nullable<System.DateTime> TimeEndField;
        
        private System.Nullable<bool> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServicePosition.Boat BoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServicePosition.Port PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServicePosition.Port Port1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IDBoat {
            get {
                return this.IDBoatField;
            }
            set {
                if ((this.IDBoatField.Equals(value) != true)) {
                    this.IDBoatField = value;
                    this.RaisePropertyChanged("IDBoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> BeginPosition {
            get {
                return this.BeginPositionField;
            }
            set {
                if ((this.BeginPositionField.Equals(value) != true)) {
                    this.BeginPositionField = value;
                    this.RaisePropertyChanged("BeginPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> EndPosition {
            get {
                return this.EndPositionField;
            }
            set {
                if ((this.EndPositionField.Equals(value) != true)) {
                    this.EndPositionField = value;
                    this.RaisePropertyChanged("EndPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<double> TimeProvide {
            get {
                return this.TimeProvideField;
            }
            set {
                if ((this.TimeProvideField.Equals(value) != true)) {
                    this.TimeProvideField = value;
                    this.RaisePropertyChanged("TimeProvide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> TimeBegin {
            get {
                return this.TimeBeginField;
            }
            set {
                if ((this.TimeBeginField.Equals(value) != true)) {
                    this.TimeBeginField = value;
                    this.RaisePropertyChanged("TimeBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> TimeEnd {
            get {
                return this.TimeEndField;
            }
            set {
                if ((this.TimeEndField.Equals(value) != true)) {
                    this.TimeEndField = value;
                    this.RaisePropertyChanged("TimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public BoatManagement.ServicePosition.Boat Boat {
            get {
                return this.BoatField;
            }
            set {
                if ((object.ReferenceEquals(this.BoatField, value) != true)) {
                    this.BoatField = value;
                    this.RaisePropertyChanged("Boat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public BoatManagement.ServicePosition.Port Port {
            get {
                return this.PortField;
            }
            set {
                if ((object.ReferenceEquals(this.PortField, value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public BoatManagement.ServicePosition.Port Port1 {
            get {
                return this.Port1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Port1Field, value) != true)) {
                    this.Port1Field = value;
                    this.RaisePropertyChanged("Port1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Boat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Boat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MMSIField;
        
        private System.Nullable<int> IDNationalField;
        
        private System.Nullable<int> IDTypeBoatField;
        
        private System.Nullable<double> VolumeField;
        
        private System.Nullable<double> TonnageField;
        
        private System.Nullable<double> HighField;
        
        private System.Nullable<double> LengthField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServicePosition.National NationalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServicePosition.TypeBoat TypeBoatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMO {
            get {
                return this.IMOField;
            }
            set {
                if ((object.ReferenceEquals(this.IMOField, value) != true)) {
                    this.IMOField = value;
                    this.RaisePropertyChanged("IMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MMSI {
            get {
                return this.MMSIField;
            }
            set {
                if ((object.ReferenceEquals(this.MMSIField, value) != true)) {
                    this.MMSIField = value;
                    this.RaisePropertyChanged("MMSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> IDNational {
            get {
                return this.IDNationalField;
            }
            set {
                if ((this.IDNationalField.Equals(value) != true)) {
                    this.IDNationalField = value;
                    this.RaisePropertyChanged("IDNational");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> IDTypeBoat {
            get {
                return this.IDTypeBoatField;
            }
            set {
                if ((this.IDTypeBoatField.Equals(value) != true)) {
                    this.IDTypeBoatField = value;
                    this.RaisePropertyChanged("IDTypeBoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<double> Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<double> Tonnage {
            get {
                return this.TonnageField;
            }
            set {
                if ((this.TonnageField.Equals(value) != true)) {
                    this.TonnageField = value;
                    this.RaisePropertyChanged("Tonnage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<double> High {
            get {
                return this.HighField;
            }
            set {
                if ((this.HighField.Equals(value) != true)) {
                    this.HighField = value;
                    this.RaisePropertyChanged("High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<double> Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public BoatManagement.ServicePosition.National National {
            get {
                return this.NationalField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalField, value) != true)) {
                    this.NationalField = value;
                    this.RaisePropertyChanged("National");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public BoatManagement.ServicePosition.TypeBoat TypeBoat {
            get {
                return this.TypeBoatField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeBoatField, value) != true)) {
                    this.TypeBoatField = value;
                    this.RaisePropertyChanged("TypeBoat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Port", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Port : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<double> LongitudeField;
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<int> ID_NationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OceanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> ID_Nation {
            get {
                return this.ID_NationField;
            }
            set {
                if ((this.ID_NationField.Equals(value) != true)) {
                    this.ID_NationField = value;
                    this.RaisePropertyChanged("ID_Nation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ocean {
            get {
                return this.OceanField;
            }
            set {
                if ((object.ReferenceEquals(this.OceanField, value) != true)) {
                    this.OceanField = value;
                    this.RaisePropertyChanged("Ocean");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="National", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class National : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeBoat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TypeBoat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePosition.Position1Soap")]
    public interface Position1Soap {
        
        // CODEGEN: Generating message contract since element name ListPositionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPosition", ReplyAction="*")]
        BoatManagement.ServicePosition.ListPositionResponse ListPosition(BoatManagement.ServicePosition.ListPositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPosition", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.ListPositionResponse> ListPositionAsync(BoatManagement.ServicePosition.ListPositionRequest request);
        
        // CODEGEN: Generating message contract since element name GetPositionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosition", ReplyAction="*")]
        BoatManagement.ServicePosition.GetPositionResponse GetPosition(BoatManagement.ServicePosition.GetPositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosition", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.GetPositionResponse> GetPositionAsync(BoatManagement.ServicePosition.GetPositionRequest request);
        
        // CODEGEN: Generating message contract since element name GetPoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPo", ReplyAction="*")]
        BoatManagement.ServicePosition.GetPoResponse GetPo(BoatManagement.ServicePosition.GetPoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPo", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.GetPoResponse> GetPoAsync(BoatManagement.ServicePosition.GetPoRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllPoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPo", ReplyAction="*")]
        BoatManagement.ServicePosition.GetAllPoResponse GetAllPo(BoatManagement.ServicePosition.GetAllPoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPo", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.GetAllPoResponse> GetAllPoAsync(BoatManagement.ServicePosition.GetAllPoRequest request);
        
        // CODEGEN: Generating message contract since element name ocean from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePosition", ReplyAction="*")]
        BoatManagement.ServicePosition.UpdatePositionResponse UpdatePosition(BoatManagement.ServicePosition.UpdatePositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePosition", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.UpdatePositionResponse> UpdatePositionAsync(BoatManagement.ServicePosition.UpdatePositionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPosition", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.ListPositionRequestBody Body;
        
        public ListPositionRequest() {
        }
        
        public ListPositionRequest(BoatManagement.ServicePosition.ListPositionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPositionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_Journey;
        
        public ListPositionRequestBody() {
        }
        
        public ListPositionRequestBody(int ID_Journey) {
            this.ID_Journey = ID_Journey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPositionResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.ListPositionResponseBody Body;
        
        public ListPositionResponse() {
        }
        
        public ListPositionResponse(BoatManagement.ServicePosition.ListPositionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPositionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServicePosition.Position ListPositionResult;
        
        public ListPositionResponseBody() {
        }
        
        public ListPositionResponseBody(BoatManagement.ServicePosition.Position ListPositionResult) {
            this.ListPositionResult = ListPositionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosition", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.GetPositionRequestBody Body;
        
        public GetPositionRequest() {
        }
        
        public GetPositionRequest(BoatManagement.ServicePosition.GetPositionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPositionRequestBody {
        
        public GetPositionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPositionResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.GetPositionResponseBody Body;
        
        public GetPositionResponse() {
        }
        
        public GetPositionResponse(BoatManagement.ServicePosition.GetPositionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPositionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServicePosition.Position[] GetPositionResult;
        
        public GetPositionResponseBody() {
        }
        
        public GetPositionResponseBody(BoatManagement.ServicePosition.Position[] GetPositionResult) {
            this.GetPositionResult = GetPositionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPo", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.GetPoRequestBody Body;
        
        public GetPoRequest() {
        }
        
        public GetPoRequest(BoatManagement.ServicePosition.GetPoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDPo;
        
        public GetPoRequestBody() {
        }
        
        public GetPoRequestBody(int IDPo) {
            this.IDPo = IDPo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPoResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.GetPoResponseBody Body;
        
        public GetPoResponse() {
        }
        
        public GetPoResponse(BoatManagement.ServicePosition.GetPoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServicePosition.Position GetPoResult;
        
        public GetPoResponseBody() {
        }
        
        public GetPoResponseBody(BoatManagement.ServicePosition.Position GetPoResult) {
            this.GetPoResult = GetPoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPo", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.GetAllPoRequestBody Body;
        
        public GetAllPoRequest() {
        }
        
        public GetAllPoRequest(BoatManagement.ServicePosition.GetAllPoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idTrip;
        
        public GetAllPoRequestBody() {
        }
        
        public GetAllPoRequestBody(int idTrip) {
            this.idTrip = idTrip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPoResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.GetAllPoResponseBody Body;
        
        public GetAllPoResponse() {
        }
        
        public GetAllPoResponse(BoatManagement.ServicePosition.GetAllPoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServicePosition.Position[] GetAllPoResult;
        
        public GetAllPoResponseBody() {
        }
        
        public GetAllPoResponseBody(BoatManagement.ServicePosition.Position[] GetAllPoResult) {
            this.GetAllPoResult = GetAllPoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePosition", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.UpdatePositionRequestBody Body;
        
        public UpdatePositionRequest() {
        }
        
        public UpdatePositionRequest(BoatManagement.ServicePosition.UpdatePositionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePositionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idtrip;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float longitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ocean;
        
        public UpdatePositionRequestBody() {
        }
        
        public UpdatePositionRequestBody(int idtrip, float longitude, float latitude, System.DateTime time, string ocean) {
            this.idtrip = idtrip;
            this.longitude = longitude;
            this.latitude = latitude;
            this.time = time;
            this.ocean = ocean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePositionResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServicePosition.UpdatePositionResponseBody Body;
        
        public UpdatePositionResponse() {
        }
        
        public UpdatePositionResponse(BoatManagement.ServicePosition.UpdatePositionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePositionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdatePositionResult;
        
        public UpdatePositionResponseBody() {
        }
        
        public UpdatePositionResponseBody(bool UpdatePositionResult) {
            this.UpdatePositionResult = UpdatePositionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Position1SoapChannel : BoatManagement.ServicePosition.Position1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Position1SoapClient : System.ServiceModel.ClientBase<BoatManagement.ServicePosition.Position1Soap>, BoatManagement.ServicePosition.Position1Soap {
        
        public Position1SoapClient() {
        }
        
        public Position1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Position1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Position1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Position1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServicePosition.ListPositionResponse BoatManagement.ServicePosition.Position1Soap.ListPosition(BoatManagement.ServicePosition.ListPositionRequest request) {
            return base.Channel.ListPosition(request);
        }
        
        public BoatManagement.ServicePosition.Position ListPosition(int ID_Journey) {
            BoatManagement.ServicePosition.ListPositionRequest inValue = new BoatManagement.ServicePosition.ListPositionRequest();
            inValue.Body = new BoatManagement.ServicePosition.ListPositionRequestBody();
            inValue.Body.ID_Journey = ID_Journey;
            BoatManagement.ServicePosition.ListPositionResponse retVal = ((BoatManagement.ServicePosition.Position1Soap)(this)).ListPosition(inValue);
            return retVal.Body.ListPositionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.ListPositionResponse> BoatManagement.ServicePosition.Position1Soap.ListPositionAsync(BoatManagement.ServicePosition.ListPositionRequest request) {
            return base.Channel.ListPositionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServicePosition.ListPositionResponse> ListPositionAsync(int ID_Journey) {
            BoatManagement.ServicePosition.ListPositionRequest inValue = new BoatManagement.ServicePosition.ListPositionRequest();
            inValue.Body = new BoatManagement.ServicePosition.ListPositionRequestBody();
            inValue.Body.ID_Journey = ID_Journey;
            return ((BoatManagement.ServicePosition.Position1Soap)(this)).ListPositionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServicePosition.GetPositionResponse BoatManagement.ServicePosition.Position1Soap.GetPosition(BoatManagement.ServicePosition.GetPositionRequest request) {
            return base.Channel.GetPosition(request);
        }
        
        public BoatManagement.ServicePosition.Position[] GetPosition() {
            BoatManagement.ServicePosition.GetPositionRequest inValue = new BoatManagement.ServicePosition.GetPositionRequest();
            inValue.Body = new BoatManagement.ServicePosition.GetPositionRequestBody();
            BoatManagement.ServicePosition.GetPositionResponse retVal = ((BoatManagement.ServicePosition.Position1Soap)(this)).GetPosition(inValue);
            return retVal.Body.GetPositionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.GetPositionResponse> BoatManagement.ServicePosition.Position1Soap.GetPositionAsync(BoatManagement.ServicePosition.GetPositionRequest request) {
            return base.Channel.GetPositionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServicePosition.GetPositionResponse> GetPositionAsync() {
            BoatManagement.ServicePosition.GetPositionRequest inValue = new BoatManagement.ServicePosition.GetPositionRequest();
            inValue.Body = new BoatManagement.ServicePosition.GetPositionRequestBody();
            return ((BoatManagement.ServicePosition.Position1Soap)(this)).GetPositionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServicePosition.GetPoResponse BoatManagement.ServicePosition.Position1Soap.GetPo(BoatManagement.ServicePosition.GetPoRequest request) {
            return base.Channel.GetPo(request);
        }
        
        public BoatManagement.ServicePosition.Position GetPo(int IDPo) {
            BoatManagement.ServicePosition.GetPoRequest inValue = new BoatManagement.ServicePosition.GetPoRequest();
            inValue.Body = new BoatManagement.ServicePosition.GetPoRequestBody();
            inValue.Body.IDPo = IDPo;
            BoatManagement.ServicePosition.GetPoResponse retVal = ((BoatManagement.ServicePosition.Position1Soap)(this)).GetPo(inValue);
            return retVal.Body.GetPoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.GetPoResponse> BoatManagement.ServicePosition.Position1Soap.GetPoAsync(BoatManagement.ServicePosition.GetPoRequest request) {
            return base.Channel.GetPoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServicePosition.GetPoResponse> GetPoAsync(int IDPo) {
            BoatManagement.ServicePosition.GetPoRequest inValue = new BoatManagement.ServicePosition.GetPoRequest();
            inValue.Body = new BoatManagement.ServicePosition.GetPoRequestBody();
            inValue.Body.IDPo = IDPo;
            return ((BoatManagement.ServicePosition.Position1Soap)(this)).GetPoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServicePosition.GetAllPoResponse BoatManagement.ServicePosition.Position1Soap.GetAllPo(BoatManagement.ServicePosition.GetAllPoRequest request) {
            return base.Channel.GetAllPo(request);
        }
        
        public BoatManagement.ServicePosition.Position[] GetAllPo(int idTrip) {
            BoatManagement.ServicePosition.GetAllPoRequest inValue = new BoatManagement.ServicePosition.GetAllPoRequest();
            inValue.Body = new BoatManagement.ServicePosition.GetAllPoRequestBody();
            inValue.Body.idTrip = idTrip;
            BoatManagement.ServicePosition.GetAllPoResponse retVal = ((BoatManagement.ServicePosition.Position1Soap)(this)).GetAllPo(inValue);
            return retVal.Body.GetAllPoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.GetAllPoResponse> BoatManagement.ServicePosition.Position1Soap.GetAllPoAsync(BoatManagement.ServicePosition.GetAllPoRequest request) {
            return base.Channel.GetAllPoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServicePosition.GetAllPoResponse> GetAllPoAsync(int idTrip) {
            BoatManagement.ServicePosition.GetAllPoRequest inValue = new BoatManagement.ServicePosition.GetAllPoRequest();
            inValue.Body = new BoatManagement.ServicePosition.GetAllPoRequestBody();
            inValue.Body.idTrip = idTrip;
            return ((BoatManagement.ServicePosition.Position1Soap)(this)).GetAllPoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServicePosition.UpdatePositionResponse BoatManagement.ServicePosition.Position1Soap.UpdatePosition(BoatManagement.ServicePosition.UpdatePositionRequest request) {
            return base.Channel.UpdatePosition(request);
        }
        
        public bool UpdatePosition(int idtrip, float longitude, float latitude, System.DateTime time, string ocean) {
            BoatManagement.ServicePosition.UpdatePositionRequest inValue = new BoatManagement.ServicePosition.UpdatePositionRequest();
            inValue.Body = new BoatManagement.ServicePosition.UpdatePositionRequestBody();
            inValue.Body.idtrip = idtrip;
            inValue.Body.longitude = longitude;
            inValue.Body.latitude = latitude;
            inValue.Body.time = time;
            inValue.Body.ocean = ocean;
            BoatManagement.ServicePosition.UpdatePositionResponse retVal = ((BoatManagement.ServicePosition.Position1Soap)(this)).UpdatePosition(inValue);
            return retVal.Body.UpdatePositionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServicePosition.UpdatePositionResponse> BoatManagement.ServicePosition.Position1Soap.UpdatePositionAsync(BoatManagement.ServicePosition.UpdatePositionRequest request) {
            return base.Channel.UpdatePositionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServicePosition.UpdatePositionResponse> UpdatePositionAsync(int idtrip, float longitude, float latitude, System.DateTime time, string ocean) {
            BoatManagement.ServicePosition.UpdatePositionRequest inValue = new BoatManagement.ServicePosition.UpdatePositionRequest();
            inValue.Body = new BoatManagement.ServicePosition.UpdatePositionRequestBody();
            inValue.Body.idtrip = idtrip;
            inValue.Body.longitude = longitude;
            inValue.Body.latitude = latitude;
            inValue.Body.time = time;
            inValue.Body.ocean = ocean;
            return ((BoatManagement.ServicePosition.Position1Soap)(this)).UpdatePositionAsync(inValue);
        }
    }
}
