//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatManagement.ServiceParameter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parameter", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Parameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<int> IDPositionField;
        
        private System.Nullable<double> SpeedField;
        
        private System.Nullable<double> WaterlevelField;
        
        private System.Nullable<double> WindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeatherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceParameter.Position PositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IDPosition {
            get {
                return this.IDPositionField;
            }
            set {
                if ((this.IDPositionField.Equals(value) != true)) {
                    this.IDPositionField = value;
                    this.RaisePropertyChanged("IDPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Waterlevel {
            get {
                return this.WaterlevelField;
            }
            set {
                if ((this.WaterlevelField.Equals(value) != true)) {
                    this.WaterlevelField = value;
                    this.RaisePropertyChanged("Waterlevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Wind {
            get {
                return this.WindField;
            }
            set {
                if ((this.WindField.Equals(value) != true)) {
                    this.WindField = value;
                    this.RaisePropertyChanged("Wind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Weather {
            get {
                return this.WeatherField;
            }
            set {
                if ((object.ReferenceEquals(this.WeatherField, value) != true)) {
                    this.WeatherField = value;
                    this.RaisePropertyChanged("Weather");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BoatManagement.ServiceParameter.Position Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<int> IDJourneyField;
        
        private System.Nullable<double> LongitudeField;
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<System.DateTime> TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OceansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceParameter.Journey JourneyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IDJourney {
            get {
                return this.IDJourneyField;
            }
            set {
                if ((this.IDJourneyField.Equals(value) != true)) {
                    this.IDJourneyField = value;
                    this.RaisePropertyChanged("IDJourney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Oceans {
            get {
                return this.OceansField;
            }
            set {
                if ((object.ReferenceEquals(this.OceansField, value) != true)) {
                    this.OceansField = value;
                    this.RaisePropertyChanged("Oceans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BoatManagement.ServiceParameter.Journey Journey {
            get {
                return this.JourneyField;
            }
            set {
                if ((object.ReferenceEquals(this.JourneyField, value) != true)) {
                    this.JourneyField = value;
                    this.RaisePropertyChanged("Journey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Journey", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Journey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<int> IDBoatField;
        
        private System.Nullable<int> BeginPositionField;
        
        private System.Nullable<int> EndPositionField;
        
        private System.Nullable<double> TimeProvideField;
        
        private System.Nullable<System.DateTime> TimeBeginField;
        
        private System.Nullable<System.DateTime> TimeEndField;
        
        private System.Nullable<bool> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceParameter.Boat BoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceParameter.Port PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceParameter.Port Port1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IDBoat {
            get {
                return this.IDBoatField;
            }
            set {
                if ((this.IDBoatField.Equals(value) != true)) {
                    this.IDBoatField = value;
                    this.RaisePropertyChanged("IDBoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> BeginPosition {
            get {
                return this.BeginPositionField;
            }
            set {
                if ((this.BeginPositionField.Equals(value) != true)) {
                    this.BeginPositionField = value;
                    this.RaisePropertyChanged("BeginPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> EndPosition {
            get {
                return this.EndPositionField;
            }
            set {
                if ((this.EndPositionField.Equals(value) != true)) {
                    this.EndPositionField = value;
                    this.RaisePropertyChanged("EndPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<double> TimeProvide {
            get {
                return this.TimeProvideField;
            }
            set {
                if ((this.TimeProvideField.Equals(value) != true)) {
                    this.TimeProvideField = value;
                    this.RaisePropertyChanged("TimeProvide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> TimeBegin {
            get {
                return this.TimeBeginField;
            }
            set {
                if ((this.TimeBeginField.Equals(value) != true)) {
                    this.TimeBeginField = value;
                    this.RaisePropertyChanged("TimeBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> TimeEnd {
            get {
                return this.TimeEndField;
            }
            set {
                if ((this.TimeEndField.Equals(value) != true)) {
                    this.TimeEndField = value;
                    this.RaisePropertyChanged("TimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public BoatManagement.ServiceParameter.Boat Boat {
            get {
                return this.BoatField;
            }
            set {
                if ((object.ReferenceEquals(this.BoatField, value) != true)) {
                    this.BoatField = value;
                    this.RaisePropertyChanged("Boat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public BoatManagement.ServiceParameter.Port Port {
            get {
                return this.PortField;
            }
            set {
                if ((object.ReferenceEquals(this.PortField, value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public BoatManagement.ServiceParameter.Port Port1 {
            get {
                return this.Port1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Port1Field, value) != true)) {
                    this.Port1Field = value;
                    this.RaisePropertyChanged("Port1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Boat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Boat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MMSIField;
        
        private System.Nullable<int> IDNationalField;
        
        private System.Nullable<int> IDTypeBoatField;
        
        private System.Nullable<double> VolumeField;
        
        private System.Nullable<double> TonnageField;
        
        private System.Nullable<double> HighField;
        
        private System.Nullable<double> LengthField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceParameter.National NationalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceParameter.TypeBoat TypeBoatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMO {
            get {
                return this.IMOField;
            }
            set {
                if ((object.ReferenceEquals(this.IMOField, value) != true)) {
                    this.IMOField = value;
                    this.RaisePropertyChanged("IMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MMSI {
            get {
                return this.MMSIField;
            }
            set {
                if ((object.ReferenceEquals(this.MMSIField, value) != true)) {
                    this.MMSIField = value;
                    this.RaisePropertyChanged("MMSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> IDNational {
            get {
                return this.IDNationalField;
            }
            set {
                if ((this.IDNationalField.Equals(value) != true)) {
                    this.IDNationalField = value;
                    this.RaisePropertyChanged("IDNational");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> IDTypeBoat {
            get {
                return this.IDTypeBoatField;
            }
            set {
                if ((this.IDTypeBoatField.Equals(value) != true)) {
                    this.IDTypeBoatField = value;
                    this.RaisePropertyChanged("IDTypeBoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<double> Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<double> Tonnage {
            get {
                return this.TonnageField;
            }
            set {
                if ((this.TonnageField.Equals(value) != true)) {
                    this.TonnageField = value;
                    this.RaisePropertyChanged("Tonnage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<double> High {
            get {
                return this.HighField;
            }
            set {
                if ((this.HighField.Equals(value) != true)) {
                    this.HighField = value;
                    this.RaisePropertyChanged("High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<double> Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public BoatManagement.ServiceParameter.National National {
            get {
                return this.NationalField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalField, value) != true)) {
                    this.NationalField = value;
                    this.RaisePropertyChanged("National");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public BoatManagement.ServiceParameter.TypeBoat TypeBoat {
            get {
                return this.TypeBoatField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeBoatField, value) != true)) {
                    this.TypeBoatField = value;
                    this.RaisePropertyChanged("TypeBoat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Port", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Port : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<double> LongitudeField;
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<int> ID_NationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OceanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> ID_Nation {
            get {
                return this.ID_NationField;
            }
            set {
                if ((this.ID_NationField.Equals(value) != true)) {
                    this.ID_NationField = value;
                    this.RaisePropertyChanged("ID_Nation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ocean {
            get {
                return this.OceanField;
            }
            set {
                if ((object.ReferenceEquals(this.OceanField, value) != true)) {
                    this.OceanField = value;
                    this.RaisePropertyChanged("Ocean");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="National", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class National : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeBoat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TypeBoat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceParameter.ServiceParameterSoap")]
    public interface ServiceParameterSoap {
        
        // CODEGEN: Generating message contract since element name parameterResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/parameter", ReplyAction="*")]
        BoatManagement.ServiceParameter.parameterResponse parameter(BoatManagement.ServiceParameter.parameterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/parameter", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceParameter.parameterResponse> parameterAsync(BoatManagement.ServiceParameter.parameterRequest request);
        
        // CODEGEN: Generating message contract since element name weather from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertParameter", ReplyAction="*")]
        BoatManagement.ServiceParameter.InsertParameterResponse InsertParameter(BoatManagement.ServiceParameter.InsertParameterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertParameter", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceParameter.InsertParameterResponse> InsertParameterAsync(BoatManagement.ServiceParameter.InsertParameterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parameterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parameter", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceParameter.parameterRequestBody Body;
        
        public parameterRequest() {
        }
        
        public parameterRequest(BoatManagement.ServiceParameter.parameterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class parameterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_Position;
        
        public parameterRequestBody() {
        }
        
        public parameterRequestBody(int ID_Position) {
            this.ID_Position = ID_Position;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parameterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parameterResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceParameter.parameterResponseBody Body;
        
        public parameterResponse() {
        }
        
        public parameterResponse(BoatManagement.ServiceParameter.parameterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class parameterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceParameter.Parameter parameterResult;
        
        public parameterResponseBody() {
        }
        
        public parameterResponseBody(BoatManagement.ServiceParameter.Parameter parameterResult) {
            this.parameterResult = parameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertParameterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertParameter", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceParameter.InsertParameterRequestBody Body;
        
        public InsertParameterRequest() {
        }
        
        public InsertParameterRequest(BoatManagement.ServiceParameter.InsertParameterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertParameterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_Position;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int speed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int waterlevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int wind;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string weather;
        
        public InsertParameterRequestBody() {
        }
        
        public InsertParameterRequestBody(int ID_Position, int speed, int waterlevel, int wind, string weather) {
            this.ID_Position = ID_Position;
            this.speed = speed;
            this.waterlevel = waterlevel;
            this.wind = wind;
            this.weather = weather;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertParameterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertParameterResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceParameter.InsertParameterResponseBody Body;
        
        public InsertParameterResponse() {
        }
        
        public InsertParameterResponse(BoatManagement.ServiceParameter.InsertParameterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertParameterResponseBody {
        
        public InsertParameterResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceParameterSoapChannel : BoatManagement.ServiceParameter.ServiceParameterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceParameterSoapClient : System.ServiceModel.ClientBase<BoatManagement.ServiceParameter.ServiceParameterSoap>, BoatManagement.ServiceParameter.ServiceParameterSoap {
        
        public ServiceParameterSoapClient() {
        }
        
        public ServiceParameterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceParameterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceParameterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceParameterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceParameter.parameterResponse BoatManagement.ServiceParameter.ServiceParameterSoap.parameter(BoatManagement.ServiceParameter.parameterRequest request) {
            return base.Channel.parameter(request);
        }
        
        public BoatManagement.ServiceParameter.Parameter parameter(int ID_Position) {
            BoatManagement.ServiceParameter.parameterRequest inValue = new BoatManagement.ServiceParameter.parameterRequest();
            inValue.Body = new BoatManagement.ServiceParameter.parameterRequestBody();
            inValue.Body.ID_Position = ID_Position;
            BoatManagement.ServiceParameter.parameterResponse retVal = ((BoatManagement.ServiceParameter.ServiceParameterSoap)(this)).parameter(inValue);
            return retVal.Body.parameterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceParameter.parameterResponse> BoatManagement.ServiceParameter.ServiceParameterSoap.parameterAsync(BoatManagement.ServiceParameter.parameterRequest request) {
            return base.Channel.parameterAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceParameter.parameterResponse> parameterAsync(int ID_Position) {
            BoatManagement.ServiceParameter.parameterRequest inValue = new BoatManagement.ServiceParameter.parameterRequest();
            inValue.Body = new BoatManagement.ServiceParameter.parameterRequestBody();
            inValue.Body.ID_Position = ID_Position;
            return ((BoatManagement.ServiceParameter.ServiceParameterSoap)(this)).parameterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceParameter.InsertParameterResponse BoatManagement.ServiceParameter.ServiceParameterSoap.InsertParameter(BoatManagement.ServiceParameter.InsertParameterRequest request) {
            return base.Channel.InsertParameter(request);
        }
        
        public void InsertParameter(int ID_Position, int speed, int waterlevel, int wind, string weather) {
            BoatManagement.ServiceParameter.InsertParameterRequest inValue = new BoatManagement.ServiceParameter.InsertParameterRequest();
            inValue.Body = new BoatManagement.ServiceParameter.InsertParameterRequestBody();
            inValue.Body.ID_Position = ID_Position;
            inValue.Body.speed = speed;
            inValue.Body.waterlevel = waterlevel;
            inValue.Body.wind = wind;
            inValue.Body.weather = weather;
            BoatManagement.ServiceParameter.InsertParameterResponse retVal = ((BoatManagement.ServiceParameter.ServiceParameterSoap)(this)).InsertParameter(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceParameter.InsertParameterResponse> BoatManagement.ServiceParameter.ServiceParameterSoap.InsertParameterAsync(BoatManagement.ServiceParameter.InsertParameterRequest request) {
            return base.Channel.InsertParameterAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceParameter.InsertParameterResponse> InsertParameterAsync(int ID_Position, int speed, int waterlevel, int wind, string weather) {
            BoatManagement.ServiceParameter.InsertParameterRequest inValue = new BoatManagement.ServiceParameter.InsertParameterRequest();
            inValue.Body = new BoatManagement.ServiceParameter.InsertParameterRequestBody();
            inValue.Body.ID_Position = ID_Position;
            inValue.Body.speed = speed;
            inValue.Body.waterlevel = waterlevel;
            inValue.Body.wind = wind;
            inValue.Body.weather = weather;
            return ((BoatManagement.ServiceParameter.ServiceParameterSoap)(this)).InsertParameterAsync(inValue);
        }
    }
}
