//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatManagement.ServiceLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLogin.LoginSoap")]
    public interface LoginSoap {
        
        // CODEGEN: Generating message contract since element name account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        BoatManagement.ServiceLogin.CheckLoginResponse CheckLogin(BoatManagement.ServiceLogin.CheckLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceLogin.CheckLoginResponse> CheckLoginAsync(BoatManagement.ServiceLogin.CheckLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLogin", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceLogin.CheckLoginRequestBody Body;
        
        public CheckLoginRequest() {
        }
        
        public CheckLoginRequest(BoatManagement.ServiceLogin.CheckLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CheckLoginRequestBody() {
        }
        
        public CheckLoginRequestBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceLogin.CheckLoginResponseBody Body;
        
        public CheckLoginResponse() {
        }
        
        public CheckLoginResponse(BoatManagement.ServiceLogin.CheckLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckLoginResult;
        
        public CheckLoginResponseBody() {
        }
        
        public CheckLoginResponseBody(bool CheckLoginResult) {
            this.CheckLoginResult = CheckLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginSoapChannel : BoatManagement.ServiceLogin.LoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSoapClient : System.ServiceModel.ClientBase<BoatManagement.ServiceLogin.LoginSoap>, BoatManagement.ServiceLogin.LoginSoap {
        
        public LoginSoapClient() {
        }
        
        public LoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceLogin.CheckLoginResponse BoatManagement.ServiceLogin.LoginSoap.CheckLogin(BoatManagement.ServiceLogin.CheckLoginRequest request) {
            return base.Channel.CheckLogin(request);
        }
        
        public bool CheckLogin(string account, string password) {
            BoatManagement.ServiceLogin.CheckLoginRequest inValue = new BoatManagement.ServiceLogin.CheckLoginRequest();
            inValue.Body = new BoatManagement.ServiceLogin.CheckLoginRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            BoatManagement.ServiceLogin.CheckLoginResponse retVal = ((BoatManagement.ServiceLogin.LoginSoap)(this)).CheckLogin(inValue);
            return retVal.Body.CheckLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceLogin.CheckLoginResponse> BoatManagement.ServiceLogin.LoginSoap.CheckLoginAsync(BoatManagement.ServiceLogin.CheckLoginRequest request) {
            return base.Channel.CheckLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceLogin.CheckLoginResponse> CheckLoginAsync(string account, string password) {
            BoatManagement.ServiceLogin.CheckLoginRequest inValue = new BoatManagement.ServiceLogin.CheckLoginRequest();
            inValue.Body = new BoatManagement.ServiceLogin.CheckLoginRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            return ((BoatManagement.ServiceLogin.LoginSoap)(this)).CheckLoginAsync(inValue);
        }
    }
}
