//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatManagement.ServiceJourney {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Journey", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Journey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<int> IDBoatField;
        
        private System.Nullable<int> BeginPositionField;
        
        private System.Nullable<int> EndPositionField;
        
        private System.Nullable<double> TimeProvideField;
        
        private System.Nullable<System.DateTime> TimeBeginField;
        
        private System.Nullable<System.DateTime> TimeEndField;
        
        private System.Nullable<bool> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceJourney.Boat BoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceJourney.Port PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceJourney.Port Port1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IDBoat {
            get {
                return this.IDBoatField;
            }
            set {
                if ((this.IDBoatField.Equals(value) != true)) {
                    this.IDBoatField = value;
                    this.RaisePropertyChanged("IDBoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> BeginPosition {
            get {
                return this.BeginPositionField;
            }
            set {
                if ((this.BeginPositionField.Equals(value) != true)) {
                    this.BeginPositionField = value;
                    this.RaisePropertyChanged("BeginPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> EndPosition {
            get {
                return this.EndPositionField;
            }
            set {
                if ((this.EndPositionField.Equals(value) != true)) {
                    this.EndPositionField = value;
                    this.RaisePropertyChanged("EndPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<double> TimeProvide {
            get {
                return this.TimeProvideField;
            }
            set {
                if ((this.TimeProvideField.Equals(value) != true)) {
                    this.TimeProvideField = value;
                    this.RaisePropertyChanged("TimeProvide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> TimeBegin {
            get {
                return this.TimeBeginField;
            }
            set {
                if ((this.TimeBeginField.Equals(value) != true)) {
                    this.TimeBeginField = value;
                    this.RaisePropertyChanged("TimeBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> TimeEnd {
            get {
                return this.TimeEndField;
            }
            set {
                if ((this.TimeEndField.Equals(value) != true)) {
                    this.TimeEndField = value;
                    this.RaisePropertyChanged("TimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public BoatManagement.ServiceJourney.Boat Boat {
            get {
                return this.BoatField;
            }
            set {
                if ((object.ReferenceEquals(this.BoatField, value) != true)) {
                    this.BoatField = value;
                    this.RaisePropertyChanged("Boat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public BoatManagement.ServiceJourney.Port Port {
            get {
                return this.PortField;
            }
            set {
                if ((object.ReferenceEquals(this.PortField, value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public BoatManagement.ServiceJourney.Port Port1 {
            get {
                return this.Port1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Port1Field, value) != true)) {
                    this.Port1Field = value;
                    this.RaisePropertyChanged("Port1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Boat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Boat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MMSIField;
        
        private System.Nullable<int> IDNationalField;
        
        private System.Nullable<int> IDTypeBoatField;
        
        private System.Nullable<double> VolumeField;
        
        private System.Nullable<double> TonnageField;
        
        private System.Nullable<double> HighField;
        
        private System.Nullable<double> LengthField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceJourney.National NationalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceJourney.TypeBoat TypeBoatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMO {
            get {
                return this.IMOField;
            }
            set {
                if ((object.ReferenceEquals(this.IMOField, value) != true)) {
                    this.IMOField = value;
                    this.RaisePropertyChanged("IMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MMSI {
            get {
                return this.MMSIField;
            }
            set {
                if ((object.ReferenceEquals(this.MMSIField, value) != true)) {
                    this.MMSIField = value;
                    this.RaisePropertyChanged("MMSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> IDNational {
            get {
                return this.IDNationalField;
            }
            set {
                if ((this.IDNationalField.Equals(value) != true)) {
                    this.IDNationalField = value;
                    this.RaisePropertyChanged("IDNational");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> IDTypeBoat {
            get {
                return this.IDTypeBoatField;
            }
            set {
                if ((this.IDTypeBoatField.Equals(value) != true)) {
                    this.IDTypeBoatField = value;
                    this.RaisePropertyChanged("IDTypeBoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<double> Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<double> Tonnage {
            get {
                return this.TonnageField;
            }
            set {
                if ((this.TonnageField.Equals(value) != true)) {
                    this.TonnageField = value;
                    this.RaisePropertyChanged("Tonnage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<double> High {
            get {
                return this.HighField;
            }
            set {
                if ((this.HighField.Equals(value) != true)) {
                    this.HighField = value;
                    this.RaisePropertyChanged("High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<double> Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public BoatManagement.ServiceJourney.National National {
            get {
                return this.NationalField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalField, value) != true)) {
                    this.NationalField = value;
                    this.RaisePropertyChanged("National");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public BoatManagement.ServiceJourney.TypeBoat TypeBoat {
            get {
                return this.TypeBoatField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeBoatField, value) != true)) {
                    this.TypeBoatField = value;
                    this.RaisePropertyChanged("TypeBoat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Port", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Port : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<double> LongitudeField;
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<int> ID_NationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OceanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> ID_Nation {
            get {
                return this.ID_NationField;
            }
            set {
                if ((this.ID_NationField.Equals(value) != true)) {
                    this.ID_NationField = value;
                    this.RaisePropertyChanged("ID_Nation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ocean {
            get {
                return this.OceanField;
            }
            set {
                if ((object.ReferenceEquals(this.OceanField, value) != true)) {
                    this.OceanField = value;
                    this.RaisePropertyChanged("Ocean");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="National", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class National : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeBoat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TypeBoat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceJourney.Journey1Soap")]
    public interface Journey1Soap {
        
        // CODEGEN: Generating message contract since element name LoadJourneyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadJourney", ReplyAction="*")]
        BoatManagement.ServiceJourney.LoadJourneyResponse LoadJourney(BoatManagement.ServiceJourney.LoadJourneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadJourney", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.LoadJourneyResponse> LoadJourneyAsync(BoatManagement.ServiceJourney.LoadJourneyRequest request);
        
        // CODEGEN: Generating message contract since element name LoadJourneyActiveResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadJourneyActive", ReplyAction="*")]
        BoatManagement.ServiceJourney.LoadJourneyActiveResponse LoadJourneyActive(BoatManagement.ServiceJourney.LoadJourneyActiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadJourneyActive", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.LoadJourneyActiveResponse> LoadJourneyActiveAsync(BoatManagement.ServiceJourney.LoadJourneyActiveRequest request);
        
        // CODEGEN: Generating message contract since element name GetTripResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrip", ReplyAction="*")]
        BoatManagement.ServiceJourney.GetTripResponse GetTrip(BoatManagement.ServiceJourney.GetTripRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrip", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.GetTripResponse> GetTripAsync(BoatManagement.ServiceJourney.GetTripRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllPortResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPort", ReplyAction="*")]
        BoatManagement.ServiceJourney.GetAllPortResponse GetAllPort(BoatManagement.ServiceJourney.GetAllPortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPort", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.GetAllPortResponse> GetAllPortAsync(BoatManagement.ServiceJourney.GetAllPortRequest request);
        
        // CODEGEN: Generating message contract since element name GetTripIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTripId", ReplyAction="*")]
        BoatManagement.ServiceJourney.GetTripIdResponse GetTripId(BoatManagement.ServiceJourney.GetTripIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTripId", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.GetTripIdResponse> GetTripIdAsync(BoatManagement.ServiceJourney.GetTripIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inserttrip", ReplyAction="*")]
        bool inserttrip(int Idboat, int beginposition, int endposition, float timeprovide, System.DateTime timebegin, System.DateTime timeend, bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inserttrip", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> inserttripAsync(int Idboat, int beginposition, int endposition, float timeprovide, System.DateTime timebegin, System.DateTime timeend, bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTrip", ReplyAction="*")]
        bool UpdateTrip(int idTrip, int Idboat, int beginposition, int endposition, float timeprovide, System.DateTime timebegin, System.DateTime timeend, bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTrip", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateTripAsync(int idTrip, int Idboat, int beginposition, int endposition, float timeprovide, System.DateTime timebegin, System.DateTime timeend, bool status);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadJourneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadJourney", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.LoadJourneyRequestBody Body;
        
        public LoadJourneyRequest() {
        }
        
        public LoadJourneyRequest(BoatManagement.ServiceJourney.LoadJourneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadJourneyRequestBody {
        
        public LoadJourneyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadJourneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadJourneyResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.LoadJourneyResponseBody Body;
        
        public LoadJourneyResponse() {
        }
        
        public LoadJourneyResponse(BoatManagement.ServiceJourney.LoadJourneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadJourneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceJourney.Journey[] LoadJourneyResult;
        
        public LoadJourneyResponseBody() {
        }
        
        public LoadJourneyResponseBody(BoatManagement.ServiceJourney.Journey[] LoadJourneyResult) {
            this.LoadJourneyResult = LoadJourneyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadJourneyActiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadJourneyActive", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.LoadJourneyActiveRequestBody Body;
        
        public LoadJourneyActiveRequest() {
        }
        
        public LoadJourneyActiveRequest(BoatManagement.ServiceJourney.LoadJourneyActiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadJourneyActiveRequestBody {
        
        public LoadJourneyActiveRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadJourneyActiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadJourneyActiveResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.LoadJourneyActiveResponseBody Body;
        
        public LoadJourneyActiveResponse() {
        }
        
        public LoadJourneyActiveResponse(BoatManagement.ServiceJourney.LoadJourneyActiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadJourneyActiveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceJourney.Journey[] LoadJourneyActiveResult;
        
        public LoadJourneyActiveResponseBody() {
        }
        
        public LoadJourneyActiveResponseBody(BoatManagement.ServiceJourney.Journey[] LoadJourneyActiveResult) {
            this.LoadJourneyActiveResult = LoadJourneyActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTripRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTrip", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.GetTripRequestBody Body;
        
        public GetTripRequest() {
        }
        
        public GetTripRequest(BoatManagement.ServiceJourney.GetTripRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTripRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDBoat;
        
        public GetTripRequestBody() {
        }
        
        public GetTripRequestBody(int IDBoat) {
            this.IDBoat = IDBoat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTripResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTripResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.GetTripResponseBody Body;
        
        public GetTripResponse() {
        }
        
        public GetTripResponse(BoatManagement.ServiceJourney.GetTripResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTripResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceJourney.Journey[] GetTripResult;
        
        public GetTripResponseBody() {
        }
        
        public GetTripResponseBody(BoatManagement.ServiceJourney.Journey[] GetTripResult) {
            this.GetTripResult = GetTripResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPort", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.GetAllPortRequestBody Body;
        
        public GetAllPortRequest() {
        }
        
        public GetAllPortRequest(BoatManagement.ServiceJourney.GetAllPortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPortRequestBody {
        
        public GetAllPortRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPortResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.GetAllPortResponseBody Body;
        
        public GetAllPortResponse() {
        }
        
        public GetAllPortResponse(BoatManagement.ServiceJourney.GetAllPortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceJourney.Port[] GetAllPortResult;
        
        public GetAllPortResponseBody() {
        }
        
        public GetAllPortResponseBody(BoatManagement.ServiceJourney.Port[] GetAllPortResult) {
            this.GetAllPortResult = GetAllPortResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTripIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTripId", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.GetTripIdRequestBody Body;
        
        public GetTripIdRequest() {
        }
        
        public GetTripIdRequest(BoatManagement.ServiceJourney.GetTripIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTripIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idtrip;
        
        public GetTripIdRequestBody() {
        }
        
        public GetTripIdRequestBody(int idtrip) {
            this.idtrip = idtrip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTripIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTripIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceJourney.GetTripIdResponseBody Body;
        
        public GetTripIdResponse() {
        }
        
        public GetTripIdResponse(BoatManagement.ServiceJourney.GetTripIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTripIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceJourney.Journey GetTripIdResult;
        
        public GetTripIdResponseBody() {
        }
        
        public GetTripIdResponseBody(BoatManagement.ServiceJourney.Journey GetTripIdResult) {
            this.GetTripIdResult = GetTripIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Journey1SoapChannel : BoatManagement.ServiceJourney.Journey1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Journey1SoapClient : System.ServiceModel.ClientBase<BoatManagement.ServiceJourney.Journey1Soap>, BoatManagement.ServiceJourney.Journey1Soap {
        
        public Journey1SoapClient() {
        }
        
        public Journey1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Journey1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Journey1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Journey1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceJourney.LoadJourneyResponse BoatManagement.ServiceJourney.Journey1Soap.LoadJourney(BoatManagement.ServiceJourney.LoadJourneyRequest request) {
            return base.Channel.LoadJourney(request);
        }
        
        public BoatManagement.ServiceJourney.Journey[] LoadJourney() {
            BoatManagement.ServiceJourney.LoadJourneyRequest inValue = new BoatManagement.ServiceJourney.LoadJourneyRequest();
            inValue.Body = new BoatManagement.ServiceJourney.LoadJourneyRequestBody();
            BoatManagement.ServiceJourney.LoadJourneyResponse retVal = ((BoatManagement.ServiceJourney.Journey1Soap)(this)).LoadJourney(inValue);
            return retVal.Body.LoadJourneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.LoadJourneyResponse> BoatManagement.ServiceJourney.Journey1Soap.LoadJourneyAsync(BoatManagement.ServiceJourney.LoadJourneyRequest request) {
            return base.Channel.LoadJourneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceJourney.LoadJourneyResponse> LoadJourneyAsync() {
            BoatManagement.ServiceJourney.LoadJourneyRequest inValue = new BoatManagement.ServiceJourney.LoadJourneyRequest();
            inValue.Body = new BoatManagement.ServiceJourney.LoadJourneyRequestBody();
            return ((BoatManagement.ServiceJourney.Journey1Soap)(this)).LoadJourneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceJourney.LoadJourneyActiveResponse BoatManagement.ServiceJourney.Journey1Soap.LoadJourneyActive(BoatManagement.ServiceJourney.LoadJourneyActiveRequest request) {
            return base.Channel.LoadJourneyActive(request);
        }
        
        public BoatManagement.ServiceJourney.Journey[] LoadJourneyActive() {
            BoatManagement.ServiceJourney.LoadJourneyActiveRequest inValue = new BoatManagement.ServiceJourney.LoadJourneyActiveRequest();
            inValue.Body = new BoatManagement.ServiceJourney.LoadJourneyActiveRequestBody();
            BoatManagement.ServiceJourney.LoadJourneyActiveResponse retVal = ((BoatManagement.ServiceJourney.Journey1Soap)(this)).LoadJourneyActive(inValue);
            return retVal.Body.LoadJourneyActiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.LoadJourneyActiveResponse> BoatManagement.ServiceJourney.Journey1Soap.LoadJourneyActiveAsync(BoatManagement.ServiceJourney.LoadJourneyActiveRequest request) {
            return base.Channel.LoadJourneyActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceJourney.LoadJourneyActiveResponse> LoadJourneyActiveAsync() {
            BoatManagement.ServiceJourney.LoadJourneyActiveRequest inValue = new BoatManagement.ServiceJourney.LoadJourneyActiveRequest();
            inValue.Body = new BoatManagement.ServiceJourney.LoadJourneyActiveRequestBody();
            return ((BoatManagement.ServiceJourney.Journey1Soap)(this)).LoadJourneyActiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceJourney.GetTripResponse BoatManagement.ServiceJourney.Journey1Soap.GetTrip(BoatManagement.ServiceJourney.GetTripRequest request) {
            return base.Channel.GetTrip(request);
        }
        
        public BoatManagement.ServiceJourney.Journey[] GetTrip(int IDBoat) {
            BoatManagement.ServiceJourney.GetTripRequest inValue = new BoatManagement.ServiceJourney.GetTripRequest();
            inValue.Body = new BoatManagement.ServiceJourney.GetTripRequestBody();
            inValue.Body.IDBoat = IDBoat;
            BoatManagement.ServiceJourney.GetTripResponse retVal = ((BoatManagement.ServiceJourney.Journey1Soap)(this)).GetTrip(inValue);
            return retVal.Body.GetTripResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.GetTripResponse> BoatManagement.ServiceJourney.Journey1Soap.GetTripAsync(BoatManagement.ServiceJourney.GetTripRequest request) {
            return base.Channel.GetTripAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceJourney.GetTripResponse> GetTripAsync(int IDBoat) {
            BoatManagement.ServiceJourney.GetTripRequest inValue = new BoatManagement.ServiceJourney.GetTripRequest();
            inValue.Body = new BoatManagement.ServiceJourney.GetTripRequestBody();
            inValue.Body.IDBoat = IDBoat;
            return ((BoatManagement.ServiceJourney.Journey1Soap)(this)).GetTripAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceJourney.GetAllPortResponse BoatManagement.ServiceJourney.Journey1Soap.GetAllPort(BoatManagement.ServiceJourney.GetAllPortRequest request) {
            return base.Channel.GetAllPort(request);
        }
        
        public BoatManagement.ServiceJourney.Port[] GetAllPort() {
            BoatManagement.ServiceJourney.GetAllPortRequest inValue = new BoatManagement.ServiceJourney.GetAllPortRequest();
            inValue.Body = new BoatManagement.ServiceJourney.GetAllPortRequestBody();
            BoatManagement.ServiceJourney.GetAllPortResponse retVal = ((BoatManagement.ServiceJourney.Journey1Soap)(this)).GetAllPort(inValue);
            return retVal.Body.GetAllPortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.GetAllPortResponse> BoatManagement.ServiceJourney.Journey1Soap.GetAllPortAsync(BoatManagement.ServiceJourney.GetAllPortRequest request) {
            return base.Channel.GetAllPortAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceJourney.GetAllPortResponse> GetAllPortAsync() {
            BoatManagement.ServiceJourney.GetAllPortRequest inValue = new BoatManagement.ServiceJourney.GetAllPortRequest();
            inValue.Body = new BoatManagement.ServiceJourney.GetAllPortRequestBody();
            return ((BoatManagement.ServiceJourney.Journey1Soap)(this)).GetAllPortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceJourney.GetTripIdResponse BoatManagement.ServiceJourney.Journey1Soap.GetTripId(BoatManagement.ServiceJourney.GetTripIdRequest request) {
            return base.Channel.GetTripId(request);
        }
        
        public BoatManagement.ServiceJourney.Journey GetTripId(int idtrip) {
            BoatManagement.ServiceJourney.GetTripIdRequest inValue = new BoatManagement.ServiceJourney.GetTripIdRequest();
            inValue.Body = new BoatManagement.ServiceJourney.GetTripIdRequestBody();
            inValue.Body.idtrip = idtrip;
            BoatManagement.ServiceJourney.GetTripIdResponse retVal = ((BoatManagement.ServiceJourney.Journey1Soap)(this)).GetTripId(inValue);
            return retVal.Body.GetTripIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceJourney.GetTripIdResponse> BoatManagement.ServiceJourney.Journey1Soap.GetTripIdAsync(BoatManagement.ServiceJourney.GetTripIdRequest request) {
            return base.Channel.GetTripIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceJourney.GetTripIdResponse> GetTripIdAsync(int idtrip) {
            BoatManagement.ServiceJourney.GetTripIdRequest inValue = new BoatManagement.ServiceJourney.GetTripIdRequest();
            inValue.Body = new BoatManagement.ServiceJourney.GetTripIdRequestBody();
            inValue.Body.idtrip = idtrip;
            return ((BoatManagement.ServiceJourney.Journey1Soap)(this)).GetTripIdAsync(inValue);
        }
        
        public bool inserttrip(int Idboat, int beginposition, int endposition, float timeprovide, System.DateTime timebegin, System.DateTime timeend, bool status) {
            return base.Channel.inserttrip(Idboat, beginposition, endposition, timeprovide, timebegin, timeend, status);
        }
        
        public System.Threading.Tasks.Task<bool> inserttripAsync(int Idboat, int beginposition, int endposition, float timeprovide, System.DateTime timebegin, System.DateTime timeend, bool status) {
            return base.Channel.inserttripAsync(Idboat, beginposition, endposition, timeprovide, timebegin, timeend, status);
        }
        
        public bool UpdateTrip(int idTrip, int Idboat, int beginposition, int endposition, float timeprovide, System.DateTime timebegin, System.DateTime timeend, bool status) {
            return base.Channel.UpdateTrip(idTrip, Idboat, beginposition, endposition, timeprovide, timebegin, timeend, status);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTripAsync(int idTrip, int Idboat, int beginposition, int endposition, float timeprovide, System.DateTime timebegin, System.DateTime timeend, bool status) {
            return base.Channel.UpdateTripAsync(idTrip, Idboat, beginposition, endposition, timeprovide, timebegin, timeend, status);
        }
    }
}
