//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatManagement.ServiceBoat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Boat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Boat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MMSIField;
        
        private System.Nullable<int> IDNationalField;
        
        private System.Nullable<int> IDTypeBoatField;
        
        private System.Nullable<double> VolumeField;
        
        private System.Nullable<double> TonnageField;
        
        private System.Nullable<double> HighField;
        
        private System.Nullable<double> LengthField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceBoat.National NationalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoatManagement.ServiceBoat.TypeBoat TypeBoatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMO {
            get {
                return this.IMOField;
            }
            set {
                if ((object.ReferenceEquals(this.IMOField, value) != true)) {
                    this.IMOField = value;
                    this.RaisePropertyChanged("IMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MMSI {
            get {
                return this.MMSIField;
            }
            set {
                if ((object.ReferenceEquals(this.MMSIField, value) != true)) {
                    this.MMSIField = value;
                    this.RaisePropertyChanged("MMSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> IDNational {
            get {
                return this.IDNationalField;
            }
            set {
                if ((this.IDNationalField.Equals(value) != true)) {
                    this.IDNationalField = value;
                    this.RaisePropertyChanged("IDNational");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> IDTypeBoat {
            get {
                return this.IDTypeBoatField;
            }
            set {
                if ((this.IDTypeBoatField.Equals(value) != true)) {
                    this.IDTypeBoatField = value;
                    this.RaisePropertyChanged("IDTypeBoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<double> Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<double> Tonnage {
            get {
                return this.TonnageField;
            }
            set {
                if ((this.TonnageField.Equals(value) != true)) {
                    this.TonnageField = value;
                    this.RaisePropertyChanged("Tonnage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<double> High {
            get {
                return this.HighField;
            }
            set {
                if ((this.HighField.Equals(value) != true)) {
                    this.HighField = value;
                    this.RaisePropertyChanged("High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<double> Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public BoatManagement.ServiceBoat.National National {
            get {
                return this.NationalField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalField, value) != true)) {
                    this.NationalField = value;
                    this.RaisePropertyChanged("National");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public BoatManagement.ServiceBoat.TypeBoat TypeBoat {
            get {
                return this.TypeBoatField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeBoatField, value) != true)) {
                    this.TypeBoatField = value;
                    this.RaisePropertyChanged("TypeBoat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="National", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class National : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeBoat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TypeBoat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoatActive", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BoatActive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMOField;
        
        private float LongiudeField;
        
        private float LatiudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OceanField;
        
        private int IDPositionField;
        
        private System.DateTime TimeField;
        
        private int ID_JourneyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMO {
            get {
                return this.IMOField;
            }
            set {
                if ((object.ReferenceEquals(this.IMOField, value) != true)) {
                    this.IMOField = value;
                    this.RaisePropertyChanged("IMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float Longiude {
            get {
                return this.LongiudeField;
            }
            set {
                if ((this.LongiudeField.Equals(value) != true)) {
                    this.LongiudeField = value;
                    this.RaisePropertyChanged("Longiude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float Latiude {
            get {
                return this.LatiudeField;
            }
            set {
                if ((this.LatiudeField.Equals(value) != true)) {
                    this.LatiudeField = value;
                    this.RaisePropertyChanged("Latiude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ocean {
            get {
                return this.OceanField;
            }
            set {
                if ((object.ReferenceEquals(this.OceanField, value) != true)) {
                    this.OceanField = value;
                    this.RaisePropertyChanged("Ocean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int IDPosition {
            get {
                return this.IDPositionField;
            }
            set {
                if ((this.IDPositionField.Equals(value) != true)) {
                    this.IDPositionField = value;
                    this.RaisePropertyChanged("IDPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int ID_Journey {
            get {
                return this.ID_JourneyField;
            }
            set {
                if ((this.ID_JourneyField.Equals(value) != true)) {
                    this.ID_JourneyField = value;
                    this.RaisePropertyChanged("ID_Journey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoatLostInfor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BoatLostInfor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<System.DateTime> LastConnectField;
        
        private System.Nullable<double> LongitudeField;
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<int> IDJourneyField;
        
        private System.Nullable<bool> StatusField;
        
        private System.Nullable<int> IDBoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OceanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> LastConnect {
            get {
                return this.LastConnectField;
            }
            set {
                if ((this.LastConnectField.Equals(value) != true)) {
                    this.LastConnectField = value;
                    this.RaisePropertyChanged("LastConnect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> IDJourney {
            get {
                return this.IDJourneyField;
            }
            set {
                if ((this.IDJourneyField.Equals(value) != true)) {
                    this.IDJourneyField = value;
                    this.RaisePropertyChanged("IDJourney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<bool> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> IDBoat {
            get {
                return this.IDBoatField;
            }
            set {
                if ((this.IDBoatField.Equals(value) != true)) {
                    this.IDBoatField = value;
                    this.RaisePropertyChanged("IDBoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Ocean {
            get {
                return this.OceanField;
            }
            set {
                if ((object.ReferenceEquals(this.OceanField, value) != true)) {
                    this.OceanField = value;
                    this.RaisePropertyChanged("Ocean");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sati", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sati : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalField;
        
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string National {
            get {
                return this.NationalField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalField, value) != true)) {
                    this.NationalField = value;
                    this.RaisePropertyChanged("National");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBoat.ServiceBoatSoap")]
    public interface ServiceBoatSoap {
        
        // CODEGEN: Generating message contract since element name GetAllBoatResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBoat", ReplyAction="*")]
        BoatManagement.ServiceBoat.GetAllBoatResponse GetAllBoat(BoatManagement.ServiceBoat.GetAllBoatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBoat", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetAllBoatResponse> GetAllBoatAsync(BoatManagement.ServiceBoat.GetAllBoatRequest request);
        
        // CODEGEN: Generating message contract since element name GetBoatResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBoat", ReplyAction="*")]
        BoatManagement.ServiceBoat.GetBoatResponse GetBoat(BoatManagement.ServiceBoat.GetBoatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBoat", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetBoatResponse> GetBoatAsync(BoatManagement.ServiceBoat.GetBoatRequest request);
        
        // CODEGEN: Generating message contract since element name GetNationalResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNational", ReplyAction="*")]
        BoatManagement.ServiceBoat.GetNationalResponse GetNational(BoatManagement.ServiceBoat.GetNationalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNational", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetNationalResponse> GetNationalAsync(BoatManagement.ServiceBoat.GetNationalRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllNationalResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNational", ReplyAction="*")]
        BoatManagement.ServiceBoat.GetAllNationalResponse GetAllNational(BoatManagement.ServiceBoat.GetAllNationalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNational", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetAllNationalResponse> GetAllNationalAsync(BoatManagement.ServiceBoat.GetAllNationalRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTypeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllType", ReplyAction="*")]
        BoatManagement.ServiceBoat.GetAllTypeResponse GetAllType(BoatManagement.ServiceBoat.GetAllTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllType", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetAllTypeResponse> GetAllTypeAsync(BoatManagement.ServiceBoat.GetAllTypeRequest request);
        
        // CODEGEN: Generating message contract since element name GetTypeBoatResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTypeBoat", ReplyAction="*")]
        BoatManagement.ServiceBoat.GetTypeBoatResponse GetTypeBoat(BoatManagement.ServiceBoat.GetTypeBoatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTypeBoat", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetTypeBoatResponse> GetTypeBoatAsync(BoatManagement.ServiceBoat.GetTypeBoatRequest request);
        
        // CODEGEN: Generating message contract since element name BoatAreActiveResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BoatAreActive", ReplyAction="*")]
        BoatManagement.ServiceBoat.BoatAreActiveResponse BoatAreActive(BoatManagement.ServiceBoat.BoatAreActiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BoatAreActive", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.BoatAreActiveResponse> BoatAreActiveAsync(BoatManagement.ServiceBoat.BoatAreActiveRequest request);
        
        // CODEGEN: Generating message contract since element name AllBoatLostInforResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllBoatLostInfor", ReplyAction="*")]
        BoatManagement.ServiceBoat.AllBoatLostInforResponse AllBoatLostInfor(BoatManagement.ServiceBoat.AllBoatLostInforRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllBoatLostInfor", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.AllBoatLostInforResponse> AllBoatLostInforAsync(BoatManagement.ServiceBoat.AllBoatLostInforRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertboat", ReplyAction="*")]
        BoatManagement.ServiceBoat.insertboatResponse insertboat(BoatManagement.ServiceBoat.insertboatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertboat", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.insertboatResponse> insertboatAsync(BoatManagement.ServiceBoat.insertboatRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBoat", ReplyAction="*")]
        BoatManagement.ServiceBoat.UpdateBoatResponse UpdateBoat(BoatManagement.ServiceBoat.UpdateBoatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBoat", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.UpdateBoatResponse> UpdateBoatAsync(BoatManagement.ServiceBoat.UpdateBoatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBoat", ReplyAction="*")]
        bool DeleteBoat(int idBoat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBoat", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteBoatAsync(int idBoat);
        
        // CODEGEN: Generating message contract since element name CountBoatResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountBoat", ReplyAction="*")]
        BoatManagement.ServiceBoat.CountBoatResponse CountBoat(BoatManagement.ServiceBoat.CountBoatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountBoat", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.CountBoatResponse> CountBoatAsync(BoatManagement.ServiceBoat.CountBoatRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBoatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBoat", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetAllBoatRequestBody Body;
        
        public GetAllBoatRequest() {
        }
        
        public GetAllBoatRequest(BoatManagement.ServiceBoat.GetAllBoatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllBoatRequestBody {
        
        public GetAllBoatRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBoatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBoatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetAllBoatResponseBody Body;
        
        public GetAllBoatResponse() {
        }
        
        public GetAllBoatResponse(BoatManagement.ServiceBoat.GetAllBoatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBoatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceBoat.Boat[] GetAllBoatResult;
        
        public GetAllBoatResponseBody() {
        }
        
        public GetAllBoatResponseBody(BoatManagement.ServiceBoat.Boat[] GetAllBoatResult) {
            this.GetAllBoatResult = GetAllBoatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBoatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBoat", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetBoatRequestBody Body;
        
        public GetBoatRequest() {
        }
        
        public GetBoatRequest(BoatManagement.ServiceBoat.GetBoatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBoatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdBoat;
        
        public GetBoatRequestBody() {
        }
        
        public GetBoatRequestBody(int IdBoat) {
            this.IdBoat = IdBoat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBoatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBoatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetBoatResponseBody Body;
        
        public GetBoatResponse() {
        }
        
        public GetBoatResponse(BoatManagement.ServiceBoat.GetBoatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBoatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceBoat.Boat GetBoatResult;
        
        public GetBoatResponseBody() {
        }
        
        public GetBoatResponseBody(BoatManagement.ServiceBoat.Boat GetBoatResult) {
            this.GetBoatResult = GetBoatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNational", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetNationalRequestBody Body;
        
        public GetNationalRequest() {
        }
        
        public GetNationalRequest(BoatManagement.ServiceBoat.GetNationalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNationalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdNational;
        
        public GetNationalRequestBody() {
        }
        
        public GetNationalRequestBody(int IdNational) {
            this.IdNational = IdNational;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNationalResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetNationalResponseBody Body;
        
        public GetNationalResponse() {
        }
        
        public GetNationalResponse(BoatManagement.ServiceBoat.GetNationalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNationalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceBoat.National GetNationalResult;
        
        public GetNationalResponseBody() {
        }
        
        public GetNationalResponseBody(BoatManagement.ServiceBoat.National GetNationalResult) {
            this.GetNationalResult = GetNationalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllNationalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllNational", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetAllNationalRequestBody Body;
        
        public GetAllNationalRequest() {
        }
        
        public GetAllNationalRequest(BoatManagement.ServiceBoat.GetAllNationalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllNationalRequestBody {
        
        public GetAllNationalRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllNationalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllNationalResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetAllNationalResponseBody Body;
        
        public GetAllNationalResponse() {
        }
        
        public GetAllNationalResponse(BoatManagement.ServiceBoat.GetAllNationalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllNationalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceBoat.National[] GetAllNationalResult;
        
        public GetAllNationalResponseBody() {
        }
        
        public GetAllNationalResponseBody(BoatManagement.ServiceBoat.National[] GetAllNationalResult) {
            this.GetAllNationalResult = GetAllNationalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllType", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetAllTypeRequestBody Body;
        
        public GetAllTypeRequest() {
        }
        
        public GetAllTypeRequest(BoatManagement.ServiceBoat.GetAllTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTypeRequestBody {
        
        public GetAllTypeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetAllTypeResponseBody Body;
        
        public GetAllTypeResponse() {
        }
        
        public GetAllTypeResponse(BoatManagement.ServiceBoat.GetAllTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceBoat.TypeBoat[] GetAllTypeResult;
        
        public GetAllTypeResponseBody() {
        }
        
        public GetAllTypeResponseBody(BoatManagement.ServiceBoat.TypeBoat[] GetAllTypeResult) {
            this.GetAllTypeResult = GetAllTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTypeBoatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTypeBoat", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetTypeBoatRequestBody Body;
        
        public GetTypeBoatRequest() {
        }
        
        public GetTypeBoatRequest(BoatManagement.ServiceBoat.GetTypeBoatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTypeBoatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdtypeBoat;
        
        public GetTypeBoatRequestBody() {
        }
        
        public GetTypeBoatRequestBody(int IdtypeBoat) {
            this.IdtypeBoat = IdtypeBoat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTypeBoatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTypeBoatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.GetTypeBoatResponseBody Body;
        
        public GetTypeBoatResponse() {
        }
        
        public GetTypeBoatResponse(BoatManagement.ServiceBoat.GetTypeBoatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTypeBoatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceBoat.TypeBoat GetTypeBoatResult;
        
        public GetTypeBoatResponseBody() {
        }
        
        public GetTypeBoatResponseBody(BoatManagement.ServiceBoat.TypeBoat GetTypeBoatResult) {
            this.GetTypeBoatResult = GetTypeBoatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BoatAreActiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BoatAreActive", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.BoatAreActiveRequestBody Body;
        
        public BoatAreActiveRequest() {
        }
        
        public BoatAreActiveRequest(BoatManagement.ServiceBoat.BoatAreActiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BoatAreActiveRequestBody {
        
        public BoatAreActiveRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BoatAreActiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BoatAreActiveResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.BoatAreActiveResponseBody Body;
        
        public BoatAreActiveResponse() {
        }
        
        public BoatAreActiveResponse(BoatManagement.ServiceBoat.BoatAreActiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BoatAreActiveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceBoat.BoatActive[] BoatAreActiveResult;
        
        public BoatAreActiveResponseBody() {
        }
        
        public BoatAreActiveResponseBody(BoatManagement.ServiceBoat.BoatActive[] BoatAreActiveResult) {
            this.BoatAreActiveResult = BoatAreActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllBoatLostInforRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllBoatLostInfor", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.AllBoatLostInforRequestBody Body;
        
        public AllBoatLostInforRequest() {
        }
        
        public AllBoatLostInforRequest(BoatManagement.ServiceBoat.AllBoatLostInforRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllBoatLostInforRequestBody {
        
        public AllBoatLostInforRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllBoatLostInforResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllBoatLostInforResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.AllBoatLostInforResponseBody Body;
        
        public AllBoatLostInforResponse() {
        }
        
        public AllBoatLostInforResponse(BoatManagement.ServiceBoat.AllBoatLostInforResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllBoatLostInforResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceBoat.BoatLostInfor[] AllBoatLostInforResult;
        
        public AllBoatLostInforResponseBody() {
        }
        
        public AllBoatLostInforResponseBody(BoatManagement.ServiceBoat.BoatLostInfor[] AllBoatLostInforResult) {
            this.AllBoatLostInforResult = AllBoatLostInforResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertboatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertboat", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.insertboatRequestBody Body;
        
        public insertboatRequest() {
        }
        
        public insertboatRequest(BoatManagement.ServiceBoat.insertboatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertboatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string imo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mmsi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idnational;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idtypeboat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public float volume;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public float tonnage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public float high;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public float length;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] image;
        
        public insertboatRequestBody() {
        }
        
        public insertboatRequestBody(string name, string imo, string mmsi, int idnational, int idtypeboat, float volume, float tonnage, float high, float length, bool status, byte[] image) {
            this.name = name;
            this.imo = imo;
            this.mmsi = mmsi;
            this.idnational = idnational;
            this.idtypeboat = idtypeboat;
            this.volume = volume;
            this.tonnage = tonnage;
            this.high = high;
            this.length = length;
            this.status = status;
            this.image = image;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertboatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertboatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.insertboatResponseBody Body;
        
        public insertboatResponse() {
        }
        
        public insertboatResponse(BoatManagement.ServiceBoat.insertboatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertboatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertboatResult;
        
        public insertboatResponseBody() {
        }
        
        public insertboatResponseBody(bool insertboatResult) {
            this.insertboatResult = insertboatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBoatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBoat", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.UpdateBoatRequestBody Body;
        
        public UpdateBoatRequest() {
        }
        
        public UpdateBoatRequest(BoatManagement.ServiceBoat.UpdateBoatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBoatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idBoat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string imo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mmsi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idnational;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int idtypeboat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public float volume;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public float tonnage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public float high;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public float length;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] image;
        
        public UpdateBoatRequestBody() {
        }
        
        public UpdateBoatRequestBody(int idBoat, string name, string imo, string mmsi, int idnational, int idtypeboat, float volume, float tonnage, float high, float length, bool status, byte[] image) {
            this.idBoat = idBoat;
            this.name = name;
            this.imo = imo;
            this.mmsi = mmsi;
            this.idnational = idnational;
            this.idtypeboat = idtypeboat;
            this.volume = volume;
            this.tonnage = tonnage;
            this.high = high;
            this.length = length;
            this.status = status;
            this.image = image;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBoatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBoatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.UpdateBoatResponseBody Body;
        
        public UpdateBoatResponse() {
        }
        
        public UpdateBoatResponse(BoatManagement.ServiceBoat.UpdateBoatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBoatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateBoatResult;
        
        public UpdateBoatResponseBody() {
        }
        
        public UpdateBoatResponseBody(bool UpdateBoatResult) {
            this.UpdateBoatResult = UpdateBoatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountBoatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountBoat", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.CountBoatRequestBody Body;
        
        public CountBoatRequest() {
        }
        
        public CountBoatRequest(BoatManagement.ServiceBoat.CountBoatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CountBoatRequestBody {
        
        public CountBoatRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountBoatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountBoatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceBoat.CountBoatResponseBody Body;
        
        public CountBoatResponse() {
        }
        
        public CountBoatResponse(BoatManagement.ServiceBoat.CountBoatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountBoatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceBoat.Sati[] CountBoatResult;
        
        public CountBoatResponseBody() {
        }
        
        public CountBoatResponseBody(BoatManagement.ServiceBoat.Sati[] CountBoatResult) {
            this.CountBoatResult = CountBoatResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceBoatSoapChannel : BoatManagement.ServiceBoat.ServiceBoatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBoatSoapClient : System.ServiceModel.ClientBase<BoatManagement.ServiceBoat.ServiceBoatSoap>, BoatManagement.ServiceBoat.ServiceBoatSoap {
        
        public ServiceBoatSoapClient() {
        }
        
        public ServiceBoatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBoatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBoatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBoatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.GetAllBoatResponse BoatManagement.ServiceBoat.ServiceBoatSoap.GetAllBoat(BoatManagement.ServiceBoat.GetAllBoatRequest request) {
            return base.Channel.GetAllBoat(request);
        }
        
        public BoatManagement.ServiceBoat.Boat[] GetAllBoat() {
            BoatManagement.ServiceBoat.GetAllBoatRequest inValue = new BoatManagement.ServiceBoat.GetAllBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetAllBoatRequestBody();
            BoatManagement.ServiceBoat.GetAllBoatResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetAllBoat(inValue);
            return retVal.Body.GetAllBoatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetAllBoatResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.GetAllBoatAsync(BoatManagement.ServiceBoat.GetAllBoatRequest request) {
            return base.Channel.GetAllBoatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetAllBoatResponse> GetAllBoatAsync() {
            BoatManagement.ServiceBoat.GetAllBoatRequest inValue = new BoatManagement.ServiceBoat.GetAllBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetAllBoatRequestBody();
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetAllBoatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.GetBoatResponse BoatManagement.ServiceBoat.ServiceBoatSoap.GetBoat(BoatManagement.ServiceBoat.GetBoatRequest request) {
            return base.Channel.GetBoat(request);
        }
        
        public BoatManagement.ServiceBoat.Boat GetBoat(int IdBoat) {
            BoatManagement.ServiceBoat.GetBoatRequest inValue = new BoatManagement.ServiceBoat.GetBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetBoatRequestBody();
            inValue.Body.IdBoat = IdBoat;
            BoatManagement.ServiceBoat.GetBoatResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetBoat(inValue);
            return retVal.Body.GetBoatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetBoatResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.GetBoatAsync(BoatManagement.ServiceBoat.GetBoatRequest request) {
            return base.Channel.GetBoatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetBoatResponse> GetBoatAsync(int IdBoat) {
            BoatManagement.ServiceBoat.GetBoatRequest inValue = new BoatManagement.ServiceBoat.GetBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetBoatRequestBody();
            inValue.Body.IdBoat = IdBoat;
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetBoatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.GetNationalResponse BoatManagement.ServiceBoat.ServiceBoatSoap.GetNational(BoatManagement.ServiceBoat.GetNationalRequest request) {
            return base.Channel.GetNational(request);
        }
        
        public BoatManagement.ServiceBoat.National GetNational(int IdNational) {
            BoatManagement.ServiceBoat.GetNationalRequest inValue = new BoatManagement.ServiceBoat.GetNationalRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetNationalRequestBody();
            inValue.Body.IdNational = IdNational;
            BoatManagement.ServiceBoat.GetNationalResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetNational(inValue);
            return retVal.Body.GetNationalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetNationalResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.GetNationalAsync(BoatManagement.ServiceBoat.GetNationalRequest request) {
            return base.Channel.GetNationalAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetNationalResponse> GetNationalAsync(int IdNational) {
            BoatManagement.ServiceBoat.GetNationalRequest inValue = new BoatManagement.ServiceBoat.GetNationalRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetNationalRequestBody();
            inValue.Body.IdNational = IdNational;
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetNationalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.GetAllNationalResponse BoatManagement.ServiceBoat.ServiceBoatSoap.GetAllNational(BoatManagement.ServiceBoat.GetAllNationalRequest request) {
            return base.Channel.GetAllNational(request);
        }
        
        public BoatManagement.ServiceBoat.National[] GetAllNational() {
            BoatManagement.ServiceBoat.GetAllNationalRequest inValue = new BoatManagement.ServiceBoat.GetAllNationalRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetAllNationalRequestBody();
            BoatManagement.ServiceBoat.GetAllNationalResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetAllNational(inValue);
            return retVal.Body.GetAllNationalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetAllNationalResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.GetAllNationalAsync(BoatManagement.ServiceBoat.GetAllNationalRequest request) {
            return base.Channel.GetAllNationalAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetAllNationalResponse> GetAllNationalAsync() {
            BoatManagement.ServiceBoat.GetAllNationalRequest inValue = new BoatManagement.ServiceBoat.GetAllNationalRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetAllNationalRequestBody();
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetAllNationalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.GetAllTypeResponse BoatManagement.ServiceBoat.ServiceBoatSoap.GetAllType(BoatManagement.ServiceBoat.GetAllTypeRequest request) {
            return base.Channel.GetAllType(request);
        }
        
        public BoatManagement.ServiceBoat.TypeBoat[] GetAllType() {
            BoatManagement.ServiceBoat.GetAllTypeRequest inValue = new BoatManagement.ServiceBoat.GetAllTypeRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetAllTypeRequestBody();
            BoatManagement.ServiceBoat.GetAllTypeResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetAllType(inValue);
            return retVal.Body.GetAllTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetAllTypeResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.GetAllTypeAsync(BoatManagement.ServiceBoat.GetAllTypeRequest request) {
            return base.Channel.GetAllTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetAllTypeResponse> GetAllTypeAsync() {
            BoatManagement.ServiceBoat.GetAllTypeRequest inValue = new BoatManagement.ServiceBoat.GetAllTypeRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetAllTypeRequestBody();
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetAllTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.GetTypeBoatResponse BoatManagement.ServiceBoat.ServiceBoatSoap.GetTypeBoat(BoatManagement.ServiceBoat.GetTypeBoatRequest request) {
            return base.Channel.GetTypeBoat(request);
        }
        
        public BoatManagement.ServiceBoat.TypeBoat GetTypeBoat(int IdtypeBoat) {
            BoatManagement.ServiceBoat.GetTypeBoatRequest inValue = new BoatManagement.ServiceBoat.GetTypeBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetTypeBoatRequestBody();
            inValue.Body.IdtypeBoat = IdtypeBoat;
            BoatManagement.ServiceBoat.GetTypeBoatResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetTypeBoat(inValue);
            return retVal.Body.GetTypeBoatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetTypeBoatResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.GetTypeBoatAsync(BoatManagement.ServiceBoat.GetTypeBoatRequest request) {
            return base.Channel.GetTypeBoatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.GetTypeBoatResponse> GetTypeBoatAsync(int IdtypeBoat) {
            BoatManagement.ServiceBoat.GetTypeBoatRequest inValue = new BoatManagement.ServiceBoat.GetTypeBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.GetTypeBoatRequestBody();
            inValue.Body.IdtypeBoat = IdtypeBoat;
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).GetTypeBoatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.BoatAreActiveResponse BoatManagement.ServiceBoat.ServiceBoatSoap.BoatAreActive(BoatManagement.ServiceBoat.BoatAreActiveRequest request) {
            return base.Channel.BoatAreActive(request);
        }
        
        public BoatManagement.ServiceBoat.BoatActive[] BoatAreActive() {
            BoatManagement.ServiceBoat.BoatAreActiveRequest inValue = new BoatManagement.ServiceBoat.BoatAreActiveRequest();
            inValue.Body = new BoatManagement.ServiceBoat.BoatAreActiveRequestBody();
            BoatManagement.ServiceBoat.BoatAreActiveResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).BoatAreActive(inValue);
            return retVal.Body.BoatAreActiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.BoatAreActiveResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.BoatAreActiveAsync(BoatManagement.ServiceBoat.BoatAreActiveRequest request) {
            return base.Channel.BoatAreActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.BoatAreActiveResponse> BoatAreActiveAsync() {
            BoatManagement.ServiceBoat.BoatAreActiveRequest inValue = new BoatManagement.ServiceBoat.BoatAreActiveRequest();
            inValue.Body = new BoatManagement.ServiceBoat.BoatAreActiveRequestBody();
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).BoatAreActiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.AllBoatLostInforResponse BoatManagement.ServiceBoat.ServiceBoatSoap.AllBoatLostInfor(BoatManagement.ServiceBoat.AllBoatLostInforRequest request) {
            return base.Channel.AllBoatLostInfor(request);
        }
        
        public BoatManagement.ServiceBoat.BoatLostInfor[] AllBoatLostInfor() {
            BoatManagement.ServiceBoat.AllBoatLostInforRequest inValue = new BoatManagement.ServiceBoat.AllBoatLostInforRequest();
            inValue.Body = new BoatManagement.ServiceBoat.AllBoatLostInforRequestBody();
            BoatManagement.ServiceBoat.AllBoatLostInforResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).AllBoatLostInfor(inValue);
            return retVal.Body.AllBoatLostInforResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.AllBoatLostInforResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.AllBoatLostInforAsync(BoatManagement.ServiceBoat.AllBoatLostInforRequest request) {
            return base.Channel.AllBoatLostInforAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.AllBoatLostInforResponse> AllBoatLostInforAsync() {
            BoatManagement.ServiceBoat.AllBoatLostInforRequest inValue = new BoatManagement.ServiceBoat.AllBoatLostInforRequest();
            inValue.Body = new BoatManagement.ServiceBoat.AllBoatLostInforRequestBody();
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).AllBoatLostInforAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.insertboatResponse BoatManagement.ServiceBoat.ServiceBoatSoap.insertboat(BoatManagement.ServiceBoat.insertboatRequest request) {
            return base.Channel.insertboat(request);
        }
        
        public bool insertboat(string name, string imo, string mmsi, int idnational, int idtypeboat, float volume, float tonnage, float high, float length, bool status, byte[] image) {
            BoatManagement.ServiceBoat.insertboatRequest inValue = new BoatManagement.ServiceBoat.insertboatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.insertboatRequestBody();
            inValue.Body.name = name;
            inValue.Body.imo = imo;
            inValue.Body.mmsi = mmsi;
            inValue.Body.idnational = idnational;
            inValue.Body.idtypeboat = idtypeboat;
            inValue.Body.volume = volume;
            inValue.Body.tonnage = tonnage;
            inValue.Body.high = high;
            inValue.Body.length = length;
            inValue.Body.status = status;
            inValue.Body.image = image;
            BoatManagement.ServiceBoat.insertboatResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).insertboat(inValue);
            return retVal.Body.insertboatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.insertboatResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.insertboatAsync(BoatManagement.ServiceBoat.insertboatRequest request) {
            return base.Channel.insertboatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.insertboatResponse> insertboatAsync(string name, string imo, string mmsi, int idnational, int idtypeboat, float volume, float tonnage, float high, float length, bool status, byte[] image) {
            BoatManagement.ServiceBoat.insertboatRequest inValue = new BoatManagement.ServiceBoat.insertboatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.insertboatRequestBody();
            inValue.Body.name = name;
            inValue.Body.imo = imo;
            inValue.Body.mmsi = mmsi;
            inValue.Body.idnational = idnational;
            inValue.Body.idtypeboat = idtypeboat;
            inValue.Body.volume = volume;
            inValue.Body.tonnage = tonnage;
            inValue.Body.high = high;
            inValue.Body.length = length;
            inValue.Body.status = status;
            inValue.Body.image = image;
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).insertboatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.UpdateBoatResponse BoatManagement.ServiceBoat.ServiceBoatSoap.UpdateBoat(BoatManagement.ServiceBoat.UpdateBoatRequest request) {
            return base.Channel.UpdateBoat(request);
        }
        
        public bool UpdateBoat(int idBoat, string name, string imo, string mmsi, int idnational, int idtypeboat, float volume, float tonnage, float high, float length, bool status, byte[] image) {
            BoatManagement.ServiceBoat.UpdateBoatRequest inValue = new BoatManagement.ServiceBoat.UpdateBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.UpdateBoatRequestBody();
            inValue.Body.idBoat = idBoat;
            inValue.Body.name = name;
            inValue.Body.imo = imo;
            inValue.Body.mmsi = mmsi;
            inValue.Body.idnational = idnational;
            inValue.Body.idtypeboat = idtypeboat;
            inValue.Body.volume = volume;
            inValue.Body.tonnage = tonnage;
            inValue.Body.high = high;
            inValue.Body.length = length;
            inValue.Body.status = status;
            inValue.Body.image = image;
            BoatManagement.ServiceBoat.UpdateBoatResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).UpdateBoat(inValue);
            return retVal.Body.UpdateBoatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.UpdateBoatResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.UpdateBoatAsync(BoatManagement.ServiceBoat.UpdateBoatRequest request) {
            return base.Channel.UpdateBoatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.UpdateBoatResponse> UpdateBoatAsync(int idBoat, string name, string imo, string mmsi, int idnational, int idtypeboat, float volume, float tonnage, float high, float length, bool status, byte[] image) {
            BoatManagement.ServiceBoat.UpdateBoatRequest inValue = new BoatManagement.ServiceBoat.UpdateBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.UpdateBoatRequestBody();
            inValue.Body.idBoat = idBoat;
            inValue.Body.name = name;
            inValue.Body.imo = imo;
            inValue.Body.mmsi = mmsi;
            inValue.Body.idnational = idnational;
            inValue.Body.idtypeboat = idtypeboat;
            inValue.Body.volume = volume;
            inValue.Body.tonnage = tonnage;
            inValue.Body.high = high;
            inValue.Body.length = length;
            inValue.Body.status = status;
            inValue.Body.image = image;
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).UpdateBoatAsync(inValue);
        }
        
        public bool DeleteBoat(int idBoat) {
            return base.Channel.DeleteBoat(idBoat);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBoatAsync(int idBoat) {
            return base.Channel.DeleteBoatAsync(idBoat);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceBoat.CountBoatResponse BoatManagement.ServiceBoat.ServiceBoatSoap.CountBoat(BoatManagement.ServiceBoat.CountBoatRequest request) {
            return base.Channel.CountBoat(request);
        }
        
        public BoatManagement.ServiceBoat.Sati[] CountBoat() {
            BoatManagement.ServiceBoat.CountBoatRequest inValue = new BoatManagement.ServiceBoat.CountBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.CountBoatRequestBody();
            BoatManagement.ServiceBoat.CountBoatResponse retVal = ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).CountBoat(inValue);
            return retVal.Body.CountBoatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceBoat.CountBoatResponse> BoatManagement.ServiceBoat.ServiceBoatSoap.CountBoatAsync(BoatManagement.ServiceBoat.CountBoatRequest request) {
            return base.Channel.CountBoatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceBoat.CountBoatResponse> CountBoatAsync() {
            BoatManagement.ServiceBoat.CountBoatRequest inValue = new BoatManagement.ServiceBoat.CountBoatRequest();
            inValue.Body = new BoatManagement.ServiceBoat.CountBoatRequestBody();
            return ((BoatManagement.ServiceBoat.ServiceBoatSoap)(this)).CountBoatAsync(inValue);
        }
    }
}
