//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatManagement.ServiceNational {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="National", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class National : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Port", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Port : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<double> LongitudeField;
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<int> ID_NationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OceanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> ID_Nation {
            get {
                return this.ID_NationField;
            }
            set {
                if ((this.ID_NationField.Equals(value) != true)) {
                    this.ID_NationField = value;
                    this.RaisePropertyChanged("ID_Nation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ocean {
            get {
                return this.OceanField;
            }
            set {
                if ((object.ReferenceEquals(this.OceanField, value) != true)) {
                    this.OceanField = value;
                    this.RaisePropertyChanged("Ocean");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNational.ServicePortNationalSoap")]
    public interface ServicePortNationalSoap {
        
        // CODEGEN: Generating message contract since element name ListNationalResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListNational", ReplyAction="*")]
        BoatManagement.ServiceNational.ListNationalResponse ListNational(BoatManagement.ServiceNational.ListNationalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListNational", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.ListNationalResponse> ListNationalAsync(BoatManagement.ServiceNational.ListNationalRequest request);
        
        // CODEGEN: Generating message contract since element name ListPortResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPort", ReplyAction="*")]
        BoatManagement.ServiceNational.ListPortResponse ListPort(BoatManagement.ServiceNational.ListPortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPort", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.ListPortResponse> ListPortAsync(BoatManagement.ServiceNational.ListPortRequest request);
        
        // CODEGEN: Generating message contract since element name ListPortOfNationalResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPortOfNational", ReplyAction="*")]
        BoatManagement.ServiceNational.ListPortOfNationalResponse ListPortOfNational(BoatManagement.ServiceNational.ListPortOfNationalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPortOfNational", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.ListPortOfNationalResponse> ListPortOfNationalAsync(BoatManagement.ServiceNational.ListPortOfNationalRequest request);
        
        // CODEGEN: Generating message contract since element name GetNationalResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNational", ReplyAction="*")]
        BoatManagement.ServiceNational.GetNationalResponse GetNational(BoatManagement.ServiceNational.GetNationalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNational", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.GetNationalResponse> GetNationalAsync(BoatManagement.ServiceNational.GetNationalRequest request);
        
        // CODEGEN: Generating message contract since element name GetPortByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPortByID", ReplyAction="*")]
        BoatManagement.ServiceNational.GetPortByIDResponse GetPortByID(BoatManagement.ServiceNational.GetPortByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPortByID", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.GetPortByIDResponse> GetPortByIDAsync(BoatManagement.ServiceNational.GetPortByIDRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNational", ReplyAction="*")]
        BoatManagement.ServiceNational.InsertNationalResponse InsertNational(BoatManagement.ServiceNational.InsertNationalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNational", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.InsertNationalResponse> InsertNationalAsync(BoatManagement.ServiceNational.InsertNationalRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNational", ReplyAction="*")]
        BoatManagement.ServiceNational.UpdateNationalResponse UpdateNational(BoatManagement.ServiceNational.UpdateNationalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNational", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.UpdateNationalResponse> UpdateNationalAsync(BoatManagement.ServiceNational.UpdateNationalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteNational", ReplyAction="*")]
        bool DeleteNational(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteNational", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteNationalAsync(int id);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPort", ReplyAction="*")]
        BoatManagement.ServiceNational.InsertPortResponse InsertPort(BoatManagement.ServiceNational.InsertPortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPort", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.InsertPortResponse> InsertPortAsync(BoatManagement.ServiceNational.InsertPortRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePort", ReplyAction="*")]
        BoatManagement.ServiceNational.UpdatePortResponse UpdatePort(BoatManagement.ServiceNational.UpdatePortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePort", ReplyAction="*")]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.UpdatePortResponse> UpdatePortAsync(BoatManagement.ServiceNational.UpdatePortRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListNationalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListNational", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.ListNationalRequestBody Body;
        
        public ListNationalRequest() {
        }
        
        public ListNationalRequest(BoatManagement.ServiceNational.ListNationalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListNationalRequestBody {
        
        public ListNationalRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListNationalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListNationalResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.ListNationalResponseBody Body;
        
        public ListNationalResponse() {
        }
        
        public ListNationalResponse(BoatManagement.ServiceNational.ListNationalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListNationalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceNational.National[] ListNationalResult;
        
        public ListNationalResponseBody() {
        }
        
        public ListNationalResponseBody(BoatManagement.ServiceNational.National[] ListNationalResult) {
            this.ListNationalResult = ListNationalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPort", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.ListPortRequestBody Body;
        
        public ListPortRequest() {
        }
        
        public ListPortRequest(BoatManagement.ServiceNational.ListPortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListPortRequestBody {
        
        public ListPortRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPortResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.ListPortResponseBody Body;
        
        public ListPortResponse() {
        }
        
        public ListPortResponse(BoatManagement.ServiceNational.ListPortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceNational.Port[] ListPortResult;
        
        public ListPortResponseBody() {
        }
        
        public ListPortResponseBody(BoatManagement.ServiceNational.Port[] ListPortResult) {
            this.ListPortResult = ListPortResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPortOfNationalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPortOfNational", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.ListPortOfNationalRequestBody Body;
        
        public ListPortOfNationalRequest() {
        }
        
        public ListPortOfNationalRequest(BoatManagement.ServiceNational.ListPortOfNationalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPortOfNationalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_Nationnal;
        
        public ListPortOfNationalRequestBody() {
        }
        
        public ListPortOfNationalRequestBody(int ID_Nationnal) {
            this.ID_Nationnal = ID_Nationnal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPortOfNationalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPortOfNationalResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.ListPortOfNationalResponseBody Body;
        
        public ListPortOfNationalResponse() {
        }
        
        public ListPortOfNationalResponse(BoatManagement.ServiceNational.ListPortOfNationalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPortOfNationalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceNational.Port[] ListPortOfNationalResult;
        
        public ListPortOfNationalResponseBody() {
        }
        
        public ListPortOfNationalResponseBody(BoatManagement.ServiceNational.Port[] ListPortOfNationalResult) {
            this.ListPortOfNationalResult = ListPortOfNationalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNational", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.GetNationalRequestBody Body;
        
        public GetNationalRequest() {
        }
        
        public GetNationalRequest(BoatManagement.ServiceNational.GetNationalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNationalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        public GetNationalRequestBody() {
        }
        
        public GetNationalRequestBody(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNationalResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.GetNationalResponseBody Body;
        
        public GetNationalResponse() {
        }
        
        public GetNationalResponse(BoatManagement.ServiceNational.GetNationalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNationalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceNational.National GetNationalResult;
        
        public GetNationalResponseBody() {
        }
        
        public GetNationalResponseBody(BoatManagement.ServiceNational.National GetNationalResult) {
            this.GetNationalResult = GetNationalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPortByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPortByID", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.GetPortByIDRequestBody Body;
        
        public GetPortByIDRequest() {
        }
        
        public GetPortByIDRequest(BoatManagement.ServiceNational.GetPortByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPortByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_port;
        
        public GetPortByIDRequestBody() {
        }
        
        public GetPortByIDRequestBody(int ID_port) {
            this.ID_port = ID_port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPortByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPortByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.GetPortByIDResponseBody Body;
        
        public GetPortByIDResponse() {
        }
        
        public GetPortByIDResponse(BoatManagement.ServiceNational.GetPortByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPortByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BoatManagement.ServiceNational.Port GetPortByIDResult;
        
        public GetPortByIDResponseBody() {
        }
        
        public GetPortByIDResponseBody(BoatManagement.ServiceNational.Port GetPortByIDResult) {
            this.GetPortByIDResult = GetPortByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNationalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNational", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.InsertNationalRequestBody Body;
        
        public InsertNationalRequest() {
        }
        
        public InsertNationalRequest(BoatManagement.ServiceNational.InsertNationalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNationalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] image;
        
        public InsertNationalRequestBody() {
        }
        
        public InsertNationalRequestBody(string name, byte[] image) {
            this.name = name;
            this.image = image;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNationalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNationalResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.InsertNationalResponseBody Body;
        
        public InsertNationalResponse() {
        }
        
        public InsertNationalResponse(BoatManagement.ServiceNational.InsertNationalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNationalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertNationalResult;
        
        public InsertNationalResponseBody() {
        }
        
        public InsertNationalResponseBody(bool InsertNationalResult) {
            this.InsertNationalResult = InsertNationalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateNationalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateNational", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.UpdateNationalRequestBody Body;
        
        public UpdateNationalRequest() {
        }
        
        public UpdateNationalRequest(BoatManagement.ServiceNational.UpdateNationalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateNationalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] image;
        
        public UpdateNationalRequestBody() {
        }
        
        public UpdateNationalRequestBody(int id, string name, byte[] image) {
            this.id = id;
            this.name = name;
            this.image = image;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateNationalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateNationalResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.UpdateNationalResponseBody Body;
        
        public UpdateNationalResponse() {
        }
        
        public UpdateNationalResponse(BoatManagement.ServiceNational.UpdateNationalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateNationalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateNationalResult;
        
        public UpdateNationalResponseBody() {
        }
        
        public UpdateNationalResponseBody(bool UpdateNationalResult) {
            this.UpdateNationalResult = UpdateNationalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPort", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.InsertPortRequestBody Body;
        
        public InsertPortRequest() {
        }
        
        public InsertPortRequest(BoatManagement.ServiceNational.InsertPortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPortRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float Lat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float Long;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int national;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Ocean;
        
        public InsertPortRequestBody() {
        }
        
        public InsertPortRequestBody(string name, float Lat, float Long, int national, string Ocean) {
            this.name = name;
            this.Lat = Lat;
            this.Long = Long;
            this.national = national;
            this.Ocean = Ocean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPortResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.InsertPortResponseBody Body;
        
        public InsertPortResponse() {
        }
        
        public InsertPortResponse(BoatManagement.ServiceNational.InsertPortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertPortResult;
        
        public InsertPortResponseBody() {
        }
        
        public InsertPortResponseBody(bool InsertPortResult) {
            this.InsertPortResult = InsertPortResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePort", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.UpdatePortRequestBody Body;
        
        public UpdatePortRequest() {
        }
        
        public UpdatePortRequest(BoatManagement.ServiceNational.UpdatePortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePortRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float Lat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float Long;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int national;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ocean;
        
        public UpdatePortRequestBody() {
        }
        
        public UpdatePortRequestBody(int id, string name, float Lat, float Long, int national, string Ocean) {
            this.id = id;
            this.name = name;
            this.Lat = Lat;
            this.Long = Long;
            this.national = national;
            this.Ocean = Ocean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePortResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoatManagement.ServiceNational.UpdatePortResponseBody Body;
        
        public UpdatePortResponse() {
        }
        
        public UpdatePortResponse(BoatManagement.ServiceNational.UpdatePortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdatePortResult;
        
        public UpdatePortResponseBody() {
        }
        
        public UpdatePortResponseBody(bool UpdatePortResult) {
            this.UpdatePortResult = UpdatePortResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicePortNationalSoapChannel : BoatManagement.ServiceNational.ServicePortNationalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePortNationalSoapClient : System.ServiceModel.ClientBase<BoatManagement.ServiceNational.ServicePortNationalSoap>, BoatManagement.ServiceNational.ServicePortNationalSoap {
        
        public ServicePortNationalSoapClient() {
        }
        
        public ServicePortNationalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePortNationalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortNationalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortNationalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceNational.ListNationalResponse BoatManagement.ServiceNational.ServicePortNationalSoap.ListNational(BoatManagement.ServiceNational.ListNationalRequest request) {
            return base.Channel.ListNational(request);
        }
        
        public BoatManagement.ServiceNational.National[] ListNational() {
            BoatManagement.ServiceNational.ListNationalRequest inValue = new BoatManagement.ServiceNational.ListNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.ListNationalRequestBody();
            BoatManagement.ServiceNational.ListNationalResponse retVal = ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).ListNational(inValue);
            return retVal.Body.ListNationalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.ListNationalResponse> BoatManagement.ServiceNational.ServicePortNationalSoap.ListNationalAsync(BoatManagement.ServiceNational.ListNationalRequest request) {
            return base.Channel.ListNationalAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceNational.ListNationalResponse> ListNationalAsync() {
            BoatManagement.ServiceNational.ListNationalRequest inValue = new BoatManagement.ServiceNational.ListNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.ListNationalRequestBody();
            return ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).ListNationalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceNational.ListPortResponse BoatManagement.ServiceNational.ServicePortNationalSoap.ListPort(BoatManagement.ServiceNational.ListPortRequest request) {
            return base.Channel.ListPort(request);
        }
        
        public BoatManagement.ServiceNational.Port[] ListPort() {
            BoatManagement.ServiceNational.ListPortRequest inValue = new BoatManagement.ServiceNational.ListPortRequest();
            inValue.Body = new BoatManagement.ServiceNational.ListPortRequestBody();
            BoatManagement.ServiceNational.ListPortResponse retVal = ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).ListPort(inValue);
            return retVal.Body.ListPortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.ListPortResponse> BoatManagement.ServiceNational.ServicePortNationalSoap.ListPortAsync(BoatManagement.ServiceNational.ListPortRequest request) {
            return base.Channel.ListPortAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceNational.ListPortResponse> ListPortAsync() {
            BoatManagement.ServiceNational.ListPortRequest inValue = new BoatManagement.ServiceNational.ListPortRequest();
            inValue.Body = new BoatManagement.ServiceNational.ListPortRequestBody();
            return ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).ListPortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceNational.ListPortOfNationalResponse BoatManagement.ServiceNational.ServicePortNationalSoap.ListPortOfNational(BoatManagement.ServiceNational.ListPortOfNationalRequest request) {
            return base.Channel.ListPortOfNational(request);
        }
        
        public BoatManagement.ServiceNational.Port[] ListPortOfNational(int ID_Nationnal) {
            BoatManagement.ServiceNational.ListPortOfNationalRequest inValue = new BoatManagement.ServiceNational.ListPortOfNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.ListPortOfNationalRequestBody();
            inValue.Body.ID_Nationnal = ID_Nationnal;
            BoatManagement.ServiceNational.ListPortOfNationalResponse retVal = ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).ListPortOfNational(inValue);
            return retVal.Body.ListPortOfNationalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.ListPortOfNationalResponse> BoatManagement.ServiceNational.ServicePortNationalSoap.ListPortOfNationalAsync(BoatManagement.ServiceNational.ListPortOfNationalRequest request) {
            return base.Channel.ListPortOfNationalAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceNational.ListPortOfNationalResponse> ListPortOfNationalAsync(int ID_Nationnal) {
            BoatManagement.ServiceNational.ListPortOfNationalRequest inValue = new BoatManagement.ServiceNational.ListPortOfNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.ListPortOfNationalRequestBody();
            inValue.Body.ID_Nationnal = ID_Nationnal;
            return ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).ListPortOfNationalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceNational.GetNationalResponse BoatManagement.ServiceNational.ServicePortNationalSoap.GetNational(BoatManagement.ServiceNational.GetNationalRequest request) {
            return base.Channel.GetNational(request);
        }
        
        public BoatManagement.ServiceNational.National GetNational(int ID) {
            BoatManagement.ServiceNational.GetNationalRequest inValue = new BoatManagement.ServiceNational.GetNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.GetNationalRequestBody();
            inValue.Body.ID = ID;
            BoatManagement.ServiceNational.GetNationalResponse retVal = ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).GetNational(inValue);
            return retVal.Body.GetNationalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.GetNationalResponse> BoatManagement.ServiceNational.ServicePortNationalSoap.GetNationalAsync(BoatManagement.ServiceNational.GetNationalRequest request) {
            return base.Channel.GetNationalAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceNational.GetNationalResponse> GetNationalAsync(int ID) {
            BoatManagement.ServiceNational.GetNationalRequest inValue = new BoatManagement.ServiceNational.GetNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.GetNationalRequestBody();
            inValue.Body.ID = ID;
            return ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).GetNationalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceNational.GetPortByIDResponse BoatManagement.ServiceNational.ServicePortNationalSoap.GetPortByID(BoatManagement.ServiceNational.GetPortByIDRequest request) {
            return base.Channel.GetPortByID(request);
        }
        
        public BoatManagement.ServiceNational.Port GetPortByID(int ID_port) {
            BoatManagement.ServiceNational.GetPortByIDRequest inValue = new BoatManagement.ServiceNational.GetPortByIDRequest();
            inValue.Body = new BoatManagement.ServiceNational.GetPortByIDRequestBody();
            inValue.Body.ID_port = ID_port;
            BoatManagement.ServiceNational.GetPortByIDResponse retVal = ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).GetPortByID(inValue);
            return retVal.Body.GetPortByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.GetPortByIDResponse> BoatManagement.ServiceNational.ServicePortNationalSoap.GetPortByIDAsync(BoatManagement.ServiceNational.GetPortByIDRequest request) {
            return base.Channel.GetPortByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceNational.GetPortByIDResponse> GetPortByIDAsync(int ID_port) {
            BoatManagement.ServiceNational.GetPortByIDRequest inValue = new BoatManagement.ServiceNational.GetPortByIDRequest();
            inValue.Body = new BoatManagement.ServiceNational.GetPortByIDRequestBody();
            inValue.Body.ID_port = ID_port;
            return ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).GetPortByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceNational.InsertNationalResponse BoatManagement.ServiceNational.ServicePortNationalSoap.InsertNational(BoatManagement.ServiceNational.InsertNationalRequest request) {
            return base.Channel.InsertNational(request);
        }
        
        public bool InsertNational(string name, byte[] image) {
            BoatManagement.ServiceNational.InsertNationalRequest inValue = new BoatManagement.ServiceNational.InsertNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.InsertNationalRequestBody();
            inValue.Body.name = name;
            inValue.Body.image = image;
            BoatManagement.ServiceNational.InsertNationalResponse retVal = ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).InsertNational(inValue);
            return retVal.Body.InsertNationalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.InsertNationalResponse> BoatManagement.ServiceNational.ServicePortNationalSoap.InsertNationalAsync(BoatManagement.ServiceNational.InsertNationalRequest request) {
            return base.Channel.InsertNationalAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceNational.InsertNationalResponse> InsertNationalAsync(string name, byte[] image) {
            BoatManagement.ServiceNational.InsertNationalRequest inValue = new BoatManagement.ServiceNational.InsertNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.InsertNationalRequestBody();
            inValue.Body.name = name;
            inValue.Body.image = image;
            return ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).InsertNationalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceNational.UpdateNationalResponse BoatManagement.ServiceNational.ServicePortNationalSoap.UpdateNational(BoatManagement.ServiceNational.UpdateNationalRequest request) {
            return base.Channel.UpdateNational(request);
        }
        
        public bool UpdateNational(int id, string name, byte[] image) {
            BoatManagement.ServiceNational.UpdateNationalRequest inValue = new BoatManagement.ServiceNational.UpdateNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.UpdateNationalRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.image = image;
            BoatManagement.ServiceNational.UpdateNationalResponse retVal = ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).UpdateNational(inValue);
            return retVal.Body.UpdateNationalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.UpdateNationalResponse> BoatManagement.ServiceNational.ServicePortNationalSoap.UpdateNationalAsync(BoatManagement.ServiceNational.UpdateNationalRequest request) {
            return base.Channel.UpdateNationalAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceNational.UpdateNationalResponse> UpdateNationalAsync(int id, string name, byte[] image) {
            BoatManagement.ServiceNational.UpdateNationalRequest inValue = new BoatManagement.ServiceNational.UpdateNationalRequest();
            inValue.Body = new BoatManagement.ServiceNational.UpdateNationalRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.image = image;
            return ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).UpdateNationalAsync(inValue);
        }
        
        public bool DeleteNational(int id) {
            return base.Channel.DeleteNational(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteNationalAsync(int id) {
            return base.Channel.DeleteNationalAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceNational.InsertPortResponse BoatManagement.ServiceNational.ServicePortNationalSoap.InsertPort(BoatManagement.ServiceNational.InsertPortRequest request) {
            return base.Channel.InsertPort(request);
        }
        
        public bool InsertPort(string name, float Lat, float Long, int national, string Ocean) {
            BoatManagement.ServiceNational.InsertPortRequest inValue = new BoatManagement.ServiceNational.InsertPortRequest();
            inValue.Body = new BoatManagement.ServiceNational.InsertPortRequestBody();
            inValue.Body.name = name;
            inValue.Body.Lat = Lat;
            inValue.Body.Long = Long;
            inValue.Body.national = national;
            inValue.Body.Ocean = Ocean;
            BoatManagement.ServiceNational.InsertPortResponse retVal = ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).InsertPort(inValue);
            return retVal.Body.InsertPortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.InsertPortResponse> BoatManagement.ServiceNational.ServicePortNationalSoap.InsertPortAsync(BoatManagement.ServiceNational.InsertPortRequest request) {
            return base.Channel.InsertPortAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceNational.InsertPortResponse> InsertPortAsync(string name, float Lat, float Long, int national, string Ocean) {
            BoatManagement.ServiceNational.InsertPortRequest inValue = new BoatManagement.ServiceNational.InsertPortRequest();
            inValue.Body = new BoatManagement.ServiceNational.InsertPortRequestBody();
            inValue.Body.name = name;
            inValue.Body.Lat = Lat;
            inValue.Body.Long = Long;
            inValue.Body.national = national;
            inValue.Body.Ocean = Ocean;
            return ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).InsertPortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoatManagement.ServiceNational.UpdatePortResponse BoatManagement.ServiceNational.ServicePortNationalSoap.UpdatePort(BoatManagement.ServiceNational.UpdatePortRequest request) {
            return base.Channel.UpdatePort(request);
        }
        
        public bool UpdatePort(int id, string name, float Lat, float Long, int national, string Ocean) {
            BoatManagement.ServiceNational.UpdatePortRequest inValue = new BoatManagement.ServiceNational.UpdatePortRequest();
            inValue.Body = new BoatManagement.ServiceNational.UpdatePortRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.Lat = Lat;
            inValue.Body.Long = Long;
            inValue.Body.national = national;
            inValue.Body.Ocean = Ocean;
            BoatManagement.ServiceNational.UpdatePortResponse retVal = ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).UpdatePort(inValue);
            return retVal.Body.UpdatePortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoatManagement.ServiceNational.UpdatePortResponse> BoatManagement.ServiceNational.ServicePortNationalSoap.UpdatePortAsync(BoatManagement.ServiceNational.UpdatePortRequest request) {
            return base.Channel.UpdatePortAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoatManagement.ServiceNational.UpdatePortResponse> UpdatePortAsync(int id, string name, float Lat, float Long, int national, string Ocean) {
            BoatManagement.ServiceNational.UpdatePortRequest inValue = new BoatManagement.ServiceNational.UpdatePortRequest();
            inValue.Body = new BoatManagement.ServiceNational.UpdatePortRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.Lat = Lat;
            inValue.Body.Long = Long;
            inValue.Body.national = national;
            inValue.Body.Ocean = Ocean;
            return ((BoatManagement.ServiceNational.ServicePortNationalSoap)(this)).UpdatePortAsync(inValue);
        }
    }
}
